### ISSUE TITLE
OpenRC shutdown is not used by Plasma

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nitrux-bug-tracker#10]
**Describe the bug**
Plasma doesn't recognize the command `openrc-shutdown` to power off or restart the computer.

**To Reproduce**
1. Invoke the Plasma log out splash.
2. Click on shutdown.
3. Nothing happens.

**Expected behavior**
Computer powers off or reboots.

**Desktop (please complete the following information):**
 - Nitrux 1.3.0 OTA-21

**Additional context**
The workaround to power off the computer is to use the terminal and run the command `sudo openrc-shutdown -p now` or `sudo openrc-shutdown -r now` to restart it.

**Comment by luis-lavaire** [comment]
Is the command `poweroff` reachable (is it available in `$PATH`)?

**Comment by UriHerrera** [comment]
No, `poweroff` is not available because the packages that supply it are `systemd-sysv` and `sysvinit-core` which conflict with `openrc`.

We can just create a symlink or an alias.

**Comment by luis-lavaire** [comment]
> We can just create a symlink or an alias.

I agree with it.

**Comment by UriHerrera** [comment]
I checked how Calculate Linux does this; they use symlinks to `halt`.
