### ISSUE TITLE
Latte Dock crashes & reboots on quit

### ISSUE THREAD

**Issue by SDK4rma** [Nitrux/nitrux-bug-tracker#103]
**Describe the bug**
I insttalled Nitrux and want to use default KDE instead of Latte Dock. 
When I try to quit it, I get a crash report "Segmentation fault" and Latte Dock restarts. 

**To Reproduce**
1. Right click on the Latte Dock
2. Select "Quit Latte"
3. A crash report appears
4. Latte Dock restarts by itself
5. See error

**Expected behavior**
I'd like to be able to use KDE without having to keep Latte Dock enabled.

**Desktop (please complete the following information):**
 - OS : Nitrux
 - Version 2.8.0

**Additional context**
Here is the crash report informations : [latte-dock-20230512-213557.txt](https://github.com/Nitrux/nitrux-bug-tracker/files/11466580/latte-dock-20230512-213557.txt)

**Comment by UriHerrera** [comment]
Go to System Settings>Startup and Shutdown>Autostart and remove Latte; this will disable Latte Dock from autostarting.

_**Disclaimer**: We do not develop or maintain Latte Dock. Bugs and problems with Latte Dock should be reported at the [KDE bug tracker](https://bugs.kde.org/)._
