### ISSUE TITLE
Flatpak apps are not added to the menu in Plasma Wayland

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nitrux-bug-tracker#114]
**Describe the bug**
For some reason, Flatpak applications are not added to the applications menu even if they work correctly.

**To Reproduce**
1. Install an app using Flatpak
2. Open the application menu
3. No launcher available

**Expected behavior**
The application is listed in the application menu

**Desktop (please complete the following information):**
 - Nitrux 2.8.1

**Additional context**
I found that this is supposedly a problem with the environment variable `XDG_DATA_DIRS`; however, this variable is added to the ZSH shell configuration file.

The file `.zshrc` already includes this line. 

`export XDG_DATA_DIRS="/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share:$HOME/.local/share/flatpak/exports:$XDG_DATA_DIRS"`

Changing to `$HOME/.local/share/flatpak/exports` doesn't have any effect.

**Comment by UriHerrera** [comment]
This is a bug in Plasma Wayland.

I switched to Plasma X11, and all the application launchers are listed. Back on Plasma Wayland, 

![Screenshot_20230531_163453](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/06b655be-8720-4551-b758-0b7da7eeaddb)
> Plasma X11

![Screenshot_20230531_163328](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/badf0498-be4a-496b-832c-c558ce1c51b7)
> Plasma Wayland

**Comment by eyduh** [comment]
I have this working on a pinebook pro running postmarketOS (edge) not sure which part is responsible for XDG_DATA_DIRS showing up under wayland on the pinebook but a quick glance shows that the KDE Frameworks is one minor version ahead ( 5.107.0 vs 5.106.0 ) and the different versions of the kernel but shouldn't affect it.

```sh
Operating System: postmarketOS edge
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.9
Kernel Version: 6.2.0 (64-bit)
Graphics Platform: Wayland
Processors: 4 × ARM Cortex-A53, 2 × ARM Cortex-A72
Memory: 3.8 GiB of RAM
Graphics Processor: Mali-T860
Product Name: Pine64 Pinebook Pro

Flatpak 1.14.4

echo $XDG_DATA_DIRS 
$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

```

vs

```sh
Operating System: Nitrux 2.8.1 build.310523.sc
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 6.3.4-1-liquorix-amd64 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i7-5600U CPU @ 2.60GHz
Memory: 7,5 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 5500
Manufacturer: LENOVO
Product Name: 20BV001AMS
System Version: ThinkPad T450

Flatpak 1.14.4

echo $XDG_DATA_DIRS 
/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share:/usr/local/share:/usr/share

```

On both systems the flatpaks are installed as system installations on `/var`

**Comment by UriHerrera** [comment]
The issue is still present even if using KDE Frameworks 5.107. The values of the variable are the same, even if they are in a different order; it shouldn't matter.

The variable is loaded immediately on login; one can check this using the command `env`.

![VirtualBox_Nitrux_2_25_06_2023_10_24_29](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/bb00c456-3276-4b5b-9005-5aee716d11c7)

![VirtualBox_Nitrux_2_25_06_2023_10_23_59](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/8f39de9e-7300-4529-8769-e6b01e095767)

In this example I installed Dolphin as system, the icon doesn't appear at all. I think that's even worse.

In X11 there's no problem.

![VirtualBox_Nitrux_2_25_06_2023_10_31_52](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/227455f7-17f4-4de8-8982-ee6a62b77a59)

![VirtualBox_Nitrux_2_25_06_2023_10_31_55](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/a43de8c2-abc6-4703-a752-9dfc3c69a809)

**Comment by UriHerrera** [comment]
Fixed in https://github.com/Nitrux/nx-desktop-settings/commit/20e485c7ef794210c68aa250a31449c4229628d0

**Comment by knulpi** [comment]
After updating to Kubuntu 24.10. with Plasma 6 Wayland, the fix in the mentioned commit was the trick to get my flatpak apps back! Ty.
(Basically adding `emulate sh -c 'source /etc/profile'` to `.zshenv` did the trick)
