### ISSUE TITLE
Display outputs are missing when using Nvidia driver

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nitrux-bug-tracker#12]
**Describe the bug**
By default, we utilize the Nvidia proprietary driver for Nvidia GPUs. However, there seems to be a problem in Laptops that utilize their Optimus technology. When the driver is used, the external display outputs are not detected _at all_.

**To Reproduce**
1. Boot our ISOs.
2. Open a terminal and run `xrandr`.
3. The output only lists a single display `eDP-1`, which is the Laptop's screen.

**Expected behavior**
The output lists all the display outputs available.

**Screenshots**
[...]

**Desktop (please complete the following information):**
- This problem affects all our ISOs.

**Additional context**
I tested with Neon, and `xrandr` does display all the outputs, so this isn't a Plasma or Kwin problem. Neon, however, doesn't use the proprietary driver. By default, it utilizes Nouveau.

I also tested with Calculate Linux to determine whether it might be an init problem, however, Calculate does display all the outputs as well. Calculate Linux also uses Nouveau by default.

The Laptop I used is a Razer Blade Advanced 2019 (Intel HD 630 and Nvidia 2070 Max-Q).

_I can't confirm the existence of this bug in Laptops with Ryzen 4000/3000 mobile CPUs with integrated Vega graphics and Nvidia discrete cards, i.e., ASUS TUF Gaming FX705DD/DT/DU._

**Comment by luis-lavaire** [comment]
Should we use Nouveau as well?

**Comment by UriHerrera** [comment]
> Should we use Nouveau as well?

The Nouveau driver doesn't work for VFIO. And for native Linux gaming the Nouveau driver is well known to underperform. We have to find a fix to make the Nvidia driver work properly.

**Comment by anibalardid** [comment]
Hi Uri ! There is my xrandr output

```
Screen 0: minimum 8 x 8, current 3840 x 1200, maximum 32767 x 32767
HDMI-0 connected 1920x1200+1920+0 (normal left inverted right x axis y axis) 550mm x 340mm
   1920x1200     59.95*+
   1920x1080     59.94  
   1680x1050     59.95  
   1600x1200     60.00  
   1440x900      59.89  
   1280x1024     60.02  
   1280x960      60.00  
   1280x800      59.81  
   1280x720      59.94  
   1024x768      60.00  
   800x600       60.32    56.25  
   720x480       59.94    59.94  
   640x480       59.94  
eDP-1-1 connected primary 1920x1080+0+120 (normal left inverted right x axis y axis) 382mm x 215mm
   1920x1080     60.05*+  60.01    59.97    59.96    48.02    59.93  
   1680x1050     59.95    60.05    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.05    60.02  
   1440x900      60.05    59.89  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    60.05    59.97    59.81    59.91  
   1152x864      60.00  
   1280x720      60.00    60.05    59.99    59.86    59.74  
   1024x768      60.05    60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.05    60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.05    60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
  1680x1050 (0x1c0) 146.250MHz -HSync +VSync
        h: width  1680 start 1784 end 1960 total 2240 skew    0 clock  65.29KHz
        v: height 1050 start 1053 end 1059 total 1089           clock  59.95Hz
  1280x1024 (0x1c3) 108.000MHz +HSync +VSync
        h: width  1280 start 1328 end 1440 total 1688 skew    0 clock  63.98KHz
        v: height 1024 start 1025 end 1028 total 1066           clock  60.02Hz
  1440x900 (0x1c2) 106.500MHz -HSync +VSync
        h: width  1440 start 1520 end 1672 total 1904 skew    0 clock  55.93KHz
        v: height  900 start  903 end  909 total  934           clock  59.89Hz
  1280x960 (0x1c4) 108.000MHz +HSync +VSync
        h: width  1280 start 1376 end 1488 total 1800 skew    0 clock  60.00KHz
        v: height  960 start  961 end  964 total 1000           clock  60.00Hz
  1280x800 (0x1c5) 83.500MHz -HSync +VSync
        h: width  1280 start 1352 end 1480 total 1680 skew    0 clock  49.70KHz
        v: height  800 start  803 end  809 total  831           clock  59.81Hz
  1024x768 (0x1c7) 65.000MHz -HSync -VSync
        h: width  1024 start 1048 end 1184 total 1344 skew    0 clock  48.36KHz
        v: height  768 start  771 end  777 total  806           clock  60.00Hz
  800x600 (0x1c8) 40.000MHz +HSync +VSync
        h: width   800 start  840 end  968 total 1056 skew    0 clock  37.88KHz
        v: height  600 start  601 end  605 total  628           clock  60.32Hz
  800x600 (0x1c9) 36.000MHz +HSync +VSync
        h: width   800 start  824 end  896 total 1024 skew    0 clock  35.16KHz
        v: height  600 start  601 end  603 total  625           clock  56.25Hz
  640x480 (0x1cc) 25.175MHz -HSync -VSync
        h: width   640 start  656 end  752 total  800 skew    0 clock  31.47KHz
        v: height  480 start  490 end  492 total  525           clock  59.94Hz

```

**Comment by UriHerrera** [comment]
Fixed in https://github.com/Nitrux/nx-desktop-settings/commit/a7f6a33f973604f989040269b2dc6708bf77e836 and https://github.com/Nitrux/nx-desktop-settings/commit/d99202ab09c43d824e622561bf0d01f94b0cc3a2

The laptop will now default to use the Nvidia GPU if available and PRIME is now available to switch beteen Nvidia and Intel.

**Comment by anibalardid** [comment]
Also, I did this things:
sudo apt-get purge nvidia*
sudo apt install linux-signed-generic
sudo apt install nvidia-driver-430 nvidia-prime

- sudo rm -f /etc/X11/xorg.conf
- make sure the package nvidia-prime is installed (sudo apt install nvidia-prime)
- switch to nvidia: 
sudo prime-select nvidia

- sudo vi /usr/share/X11/xorg.conf.d/10-amdgpu.conf
replacing only
Driver "amdgpu"
with
Driver "modesetting"

- sudo vi /usr/share/X11/xorg.conf.d/10-nvidia.conf
adding:
Option "PrimaryGPU" "Yes"
inside the OutputClass.


Please add inside the OutputClass section of /usr/share/X11/xorg.conf.d/nvidia-drm-outputclass.conf
sudo vi /usr/share/X11/xorg.conf.d/nvidia-drm-outputclass.conf
Option "AllowEmptyInitialConfiguration" "true"

- create
/etc/modprobe.d/blacklist-nouveau.conf
blacklist nouveau

- and run
sudo update-initramfs -u

also disable wayland for gdm:
You need to edit /etc/gdm3/custom.conf, change this line:

[daemon]
# Uncoment the line below to force the login screen to use Xorg
#WaylandEnable=false
to

[daemon]
# Uncoment the line below to force the login screen to use Xorg
WaylandEnable=false

**Comment by UriHerrera** [comment]
@anibalardid Can you add the output of `/usr/share/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf`?

**Comment by anibalardid** [comment]
@UriHerrera 
The file is :  /usr/share/X11/xorg.conf.d/nvidia-drm-outputclass.conf


```
# This xorg.conf.d configuration snippet configures the X server to
# automatically load the nvidia X driver when it detects a device driven by the
# nvidia-drm.ko kernel module.  Please note that this only works on Linux kernels
# version 3.9 or higher with CONFIG_DRM enabled, and only if the nvidia-drm.ko
# kernel module is loaded before the X server is started.

Section "OutputClass"
    Identifier     "nvidia"
    MatchDriver    "nvidia-drm"
    Driver         "nvidia"
    Option         "PrimaryGPU" "Yes"
    Option         "AllowEmptyInitialConfiguration" "true"
EndSection

```

**Comment by UriHerrera** [comment]
It's working fine again.
