### ISSUE TITLE
Wireless connection : stays off after stand-by 

### ISSUE THREAD

**Issue by omakuva** [Nitrux/nitrux-bug-tracker#123]
Once stand-by mode is entered, WiFi connection is dropped after resume.
Entering and leaving flight-mode does not change the behavior. 
Generally, device restart is needed.

Cf. https://linux-hardware.org/?probe=34cfa173f7

**Comment by UriHerrera** [comment]
I've added a script to `/etc/pm/sleep.d` can you test if it solves the problem for you?

**Comment by UriHerrera** [comment]
Nitrux 3.5.0 includes a script in `/etc/pm/sleep.d` can you test if it solves the problem for you?

**Comment by omakuva** [comment]
Thanks for the notification, Uri:
I was not in place to reproduce the error on the same device. 

Best thoughts and wishes,


Emanuele.

–

er | 49 1 78 1 89 1 35 1 <https://signal.org/>





7 giu 2024, 03:14 da ***@***.***:
