### ISSUE TITLE
Nuts : update is not performed 

### ISSUE THREAD

**Issue by omakuva** [Nitrux/nitrux-bug-tracker#126]
abc@xyz ~ % sudo nuts update
Nitrux Update System Tool: Success: Nitrux Update System Tool is running as root, continuing...
Nitrux Update System Tool: Success: Success! Nitrux Update System Tool configuration file found, continuing...
Nitrux Update System Tool: Info: Nitrux Update System Tool log file found, skipping...
Nitrux Update System Tool: Success: This utility is running in Nitrux. Continuing...
Nitrux Update System Tool: Success: This computer can reach the Internet. Continuing...
Nitrux Update System Tool: Info: Build list found. Continuing...
Nitrux Update System Tool: Info: Found nuts-query.info, overwriting...
Nitrux Update System Tool: Info: The current installation of Nitrux is up to date.
abc@xyz ~ % uname -a
Linux xyz 6.3.9-1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 6.3-9.1~sid (2023-06-21) x86_64 GNU/Linux

No update is performed, although Nitrux 2.9.1 has been released.

**Comment by UriHerrera** [comment]
For `nuts` to perform an update, the file it uses to check for the update needs to be updated to point to the new ISO file. It's not updated automatically when a new ISO is uploaded; this is not a bug.
