### ISSUE TITLE
Try to update

### ISSUE THREAD

**Issue by MilanTeshke** [Nitrux/nitrux-bug-tracker#13]
Hi I use "Nitrux 1.3.0 build.270620" and I am real newbie. Try to update and I got this error:

Setting up nitrux-repository-settings (0.5.0) ...
W: GPG error: http://pkgmaster.devuan.org/devuan beowulf InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 94532124541922FB
E: The repository 'http://pkgmaster.devuan.org/devuan beowulf InRelease' is not signed.
W: GPG error: http://pkgmaster.devuan.org/devuan beowulf-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 94532124541922FB

Don't know what to do.

Cheers,
Milan

**Comment by UriHerrera** [comment]
[This post in AskUbuntu solves your question](https://askubuntu.com/questions/127326/how-to-fix-missing-gpg-keys).

`apt-key adv --recv-key --keyserver keyserver.ubuntu.com 94532124541922FB`

You don't _need_ to install _any_ package.

Also, the latest version is 1.3.2 build.280820. There's no upgrade path from previous versions to 1.3.2 as these use systemd and we're not longer using systemd, we use OpenRC.

**Comment by MilanTeshke** [comment]
Thanks for answering. 

But I already made a damage. Now I am in situation where wifi modules do not work and when I want to reboot it is not possible, because I do not have that option. It is funny. 

I am newbie and pretty much I wonder in the dark so I do not know what to do, I'll figure it out somehow.

**Comment by UriHerrera** [comment]
Please open a separate issue if you have problems unrelated to this one.
