### ISSUE TITLE
File drag and drop don't work properly

### ISSUE THREAD

**Issue by dmitriisnozik** [Nitrux/nitrux-bug-tracker#139]
# Issue Description

**Describe the bug**

I had several issues with file drag and drop (especially images), as:
- Can't set wallpaper using drag and drop. All behaves normally until click on set wallpaper button, then nothing happens
- Can't upload file (tried imgur and telegram) using drag and drop (clicking on select button and then choose from directory works properly with exact same files)

**Steps to reproduce the bug**

1. Create file for further steps (e.g take screenshot)
2. Go to site where you can upload it (e.g. imgur)
3. Drag your picture and drop to upload section

**Expected behavior**

File uploads as it supposed to

**Actual behavior**

An error occured

**Screenshots**

Telegram error:
![image](https://github.com/Nitrux/nitrux-bug-tracker/assets/118886420/3faaa555-02a9-4102-840c-3cd3cdc449b7)

Imgur error:
![image](https://github.com/Nitrux/nitrux-bug-tracker/assets/118886420/0bebd402-2779-4063-b573-8a9dec2d0eb8)

**OS version and Desktop information**

Operating System: Nitrux 3.1.0 build.311023.fx
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.111.0
Qt Version: 5.15.11
Kernel Version: 6.4.15-2-liquorix-amd64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600H with Radeon Graphics
Memory: 7,2 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: ASUSTeK COMPUTER INC.
Product Name: Vivobook_ASUSLaptop M6500QH_M6500QH
System Version: 1.0

**Comment by UriHerrera** [comment]
These actions are handled by the window manager, in this case, KWin Wayland. As mentioned in the README in this bug tracker:

> You should not file a bug if you are:
> [...]
> 3. When filing a bug against software not provided by Nitrux.

We do not develop nor maintain KWin Wayland; please create a bug report at the [KDE Bug Tracker](https://bugs.kde.org/).

**Comment by UriHerrera** [comment]
Setting an image as wallpaper by dropping the image on the desktop works for me.

![ezgif com-video-to-gif](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/b5c756a2-1583-4ffb-bef1-f2feb2de4b3a)

I could drag and drop the GIF above from Index to Firefox to GitHub, and I can do the same with an image on Imgur.

![ezgif com-video-to-gif(1)](https://github.com/Nitrux/nitrux-bug-tracker/assets/3053525/1bdd15dd-031d-4a63-ab90-2f655ea51f5e)

---

Drag and drop actions are handled by the window manager, in this case, KWin Wayland. As mentioned in the README in this bug tracker:

> You should not file a bug if you are:
> [...]
> 3. Filing a bug against software not maintained or developed by Nitrux.

We do not develop nor maintain KWin Wayland; please create a bug report at the [KDE Bug Tracker](https://bugs.kde.org/).
