### ISSUE TITLE
base-passwd postinstall script hangs

### ISSUE THREAD

**Issue by boozezela** [Nitrux/nitrux-bug-tracker#15]
**Describe the bug**
I have just installed Nitrux 1.3.2 build.280820 within a VMware virtual machine, and the postinstall script for the base-passwd package hangs during the first software upgrade.
Similarly, resuming the upgrade process with `dpkg --configure -a` the script hangs as well.

**Edit**: the same happens with Nitrux 1.3.3 build.250920.

**To Reproduce**
sudo apt update
sudo apt upgrade

the process will hang at:
```
Setting up base-passwd (3.5.48)
REGISTER base-passwd/user-change-home base-passwd/system/user/irc/home/_var_run_ircd/_run_ircd
```

**Expected behavior**
The script should work out of the box.

**Workaround**
As mentioned on the public gitter channel, the script can be made to run by replacing
`#! /bin/sh` with `#! /bin/bash` within `/var/lib/dpkg/info/base-passwd.postinst`.

![Nitrux 1 3 2 build 280820 base-passwd](https://user-images.githubusercontent.com/21176382/96186007-184b3080-0f3b-11eb-846d-0ed79a295f98.jpg)

**Comment by UriHerrera** [comment]
We posted the fix on our social channels. I{m just copying it here.

> PSA: If installing a package gets it stuck during the configuration stage, you can cancel the operation with Ctrl + C and then edit its postinst script. These scripts are in /var/lib/dpkg/info, search for the corresponding script, and edit, i.e., using nano.
> Change the shebang from #/bin/sh to #/bin/bash. Then run APT again.

**Comment by boozezela** [comment]
Thanks for the clarification.
