### ISSUE TITLE
kwin_wayland segfaults on vanilla installation on Lenovo Thinkpad T14s (AMD)

### ISSUE THREAD

**Issue by rscircus** [Nitrux/nitrux-bug-tracker#150]
# Issue Description

After login only wallpaper visible.

`dmesg` says:

```
nvidia-nvlink: NvLink Core is being...
NVRM: No NVIDIA GPU found
[...]
kwin_wayland[1225x]: segfault at 0 ip ..... and so on
```

and repeats. Surprisingly, this laptop has no nvidia components. So, I don't know which bit guessed wrong there in the installation.

**Steps to reproduce the bug**

1. Have Lenovo Thinkpad T14s Gen4 AMD
2. Install the recently released `3.2.0`
3. Experience nothing working...

**Expected behavior**

1. Have Lenovo Thinkpad T14s Gen4 AMD
2. Install the recently released `3.2.0`
3. Everything works as during the live USB stick experience.

**Additional context**

Am using my MacBook Pro to type this.

**OS version and Desktop information**

Can't do this due to problem described above.

**Hardware Information using hw-probe**

Can't do this due to problem described above.

# Logs

Can't do this due to problem described above.

**Installation logs**

Can't do this due to problem described above.

_*Disclaimer*: Please report issues to the appropriate developer(s). Nitrux is a Linux distribution that comprises dozens of Free and Open Source Software projects._

**Comment by UriHerrera** [comment]
@rscircus You can still obtain logs. If you check the [tutorial to use NX Desktop](https://nxos.org/tutorial/using-nitrux-nx-desktop/), we mention using KRunner. Use KRunner to restart Plasma or open the terminal and provide the logs.

Additionally, as most Linux distributions do, TTYs are available. You can log in, open the necessary log files, take a picture, and add it to your issue.

**Comment by rscircus** [comment]
Tried an attempt with switching back to X from Plasma, which resulted in the same situation. Have access to the KRunner though. I'll try to USB-stick out the `hw.info` folder today evening.

**Comment by rscircus** [comment]
Must admit that I migrated to macos as I currently do not have too much time for such debugging sessions. I'm sorry.
