### ISSUE TITLE
Live Nitrux: password refused each time

### ISSUE THREAD

**Issue by Matgen84** [Nitrux/nitrux-bug-tracker#159]
# Issue Description

I'm using UTM to build Virtual Machine for Nitrux 3.3 Build 310124. At live login screen, usual password nitrux is not accepted.
Only solution CTRL+ALT+F2, enter login nitrux, password nitrux and type startx. Nitrux desktop appears with Installer at top left corner.

Have a nice day

**Comment by UriHerrera** [comment]
The username and the password for the Live user are both _nitrux_ (in lowercase).

Please add a video of the occurrence to confirm your problem. As is, this is unreproducible.

**Comment by UriHerrera** [comment]
Closing due to missing information and inactivity.
