### ISSUE TITLE
No EFI folder in nitrux-release-amd64_2020.11.01.iso

### ISSUE THREAD

**Issue by lfom** [Nitrux/nitrux-bug-tracker#16]
**Describe the bug**
I think it is the latest release, right? I was curious about running KDE on Wayland and the Global Menu, but the ISO does not boot in EFI mode. After mounting the ISO, it does not have an EFI folder like other distros.

**To Reproduce**
1. Download 1.3.4 release
2. Burn ISO
3. Try to boot in EFI mode
4. No boot

**Expected behavior**
Boot normally on UEFI machines.

**Screenshots**
![Screenshot from 2020-11-04 15-26-19](https://user-images.githubusercontent.com/15659999/98153977-c569f680-1eb2-11eb-92da-d6c6ff67df14.png)

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by UriHerrera** [comment]
Hi there.

The ISO does boot using EFI. Are you using VirtualBox? We do mention the following in the [changelog](https://nxos.org/changelog/changelog-nitrux-1-3-4/).

> When booting our ISO in a recent Virtualbox (6.14+) and EFI is enabled, the ISO is not booted automatically. To boot the ISO, access the Virtualbox EFI firmware pressing ESC during boot, then navigate to Boot Maintenance Manager, then Boot From File; a list of devices will be displayed; select the entry that has CDROM in it, then select the entry <efi> and press Enter, then select <boot> and press Enter, then select <bootx64.efi> and press Enter.
>
>  - VMWare Workstation does not present this problem.

Flashing the ISO to a USB and booting the Live USB in a EFI machine works without any problems. In the images below I'm booting the Live USB using a Razer Blade 15 Advanced, which uses UEFI firmware. The command I ran can confirm that I'm indeed using UEFI.

![20201104_161704](https://user-images.githubusercontent.com/3053525/98174100-e97d0600-1eb9-11eb-8c3d-3874b22393f1.jpg)
![20201104_161712](https://user-images.githubusercontent.com/3053525/98174104-ea159c80-1eb9-11eb-9bee-fd64619ff40a.jpg)



-----

> After mounting the ISO, it does not have an EFI folder like other distros.

If you notice there's an EFI image file in the ISO `efi.img`, there's also a Legacy BIOS image file `bios.img`.

**Comment by lfom** [comment]
Hello. thanks for the reply! Actually I have used Ventoy, probably it is not compatible. Maybe it is a good idea to add the folder and bootx64.efi, so it would work with more systems.

Ragards.
