### ISSUE TITLE
Graphical session fails to start, last message is "ERROR: plymouth failed to start"

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nitrux-bug-tracker#17]
**Describe the bug**
The boot process hangs at the line `ERROR: plymouth failed to start`, seemingly preventing the system from loading altogether.

**To Reproduce**
1. Install Nitrux.
2. Boot Nitrux.

**Expected behavior**
System boots and starts the user session.

**Screenshots**
![VirtualBox_Nitrux (Legacy)_06_01_2021_14_26_27](https://user-images.githubusercontent.com/3053525/103817229-e1615400-502b-11eb-87e2-c3f86e6ba66c.png)

**Desktop (please complete the following information):**
 - Nitrux.

**Additional context**
While the obvious would be to blame Plymouth, this problem doesn't appear to be related to Plymouth, to begin with. The message will be displayed whether the bootsplash is showing or not. **It's not a Plymouth error**.

(To see the output of the boot process while the bootsplash is displayed, press <kbd>Esc</kbd>, the message will be displayed briefly, even when the system continues to boot normally).

There appear to be various instances of the problem.

- One where X11 doesn't start (console output stops at the mentioned line; mouse cursor is not displayed). This instance seems to be the most common, and it appears to be related to graphics drivers. In other distributions, i.e., Ubuntu, when X11 fails to start, the user is dropped to a TTY; in our case, other TTYs are not enabled, so there's no _obvious_ indication that X11 didn't start.
- Another where X11 starts but the user is not logged in (console output stops at the mentioned line; mouse cursor is displayed). This instance is new, but it appears to be caused by a problem during system installation where the user is either invalid or not created, but the installation continues. Upon rebooting the installed system, the user is not logged in.

**Bountysource** link: https://www.bountysource.com/issues/95750918-boot-hangs-at-error-plymouth-failed-to-start

**Comment by UriHerrera** [comment]
### Update

In the latest image of Nitrux (1.3.9), the version of Plymouth that we include is 0.9.5, which's also the latest stable release, and just as I mentioned above, the message `ERROR: plymouth failed to start` is still printed to the console output. Regardless of the bootsplash showing up or not.

It looks like the first instance mentioned is the correct assessment.

In which case, we'd need to enable a second TTY when the system boots up.

**Comment by braewoods** [comment]
I'm looking to collect the bounty so I am wasking: has this been resolved already? It sounds like a low level issue that I may be able to trace.

**Comment by UriHerrera** [comment]
> I'm looking to collect the bounty so I am asking: has this been resolved already? It sounds like a low level issue that I may be able to trace.

No, it hasn't been resolved yet. There's still only one TTY being used in the distribution.

**Comment by braewoods** [comment]
I suspect this is connected to the need for openrc scripts. I'll look at that first.

**Comment by Fointard** [comment]
Hi there.
FWIW I tried to boot a live session on my brand new laptop this morning but i'm seeing that same "plymouth failed to start" error as well so you might not need a full install to reproduce.

**Comment by UriHerrera** [comment]
> Hi there.
> FWIW I tried to boot a live session on my brand new laptop this morning but i'm seeing that same "plymouth failed to start" error as well so you might not need a full install to reproduce.
> 
> Sidenote : it boots fine on my intel-based laptop but crashes on my amd-based one.

What AMD GPU do you have?. If it's a recent one it may be missing firmware (hence X11 crashes).

**Comment by Fointard** [comment]
> > Hi there.
> > FWIW I tried to boot a live session on my brand new laptop this morning but i'm seeing that same "plymouth failed to start" error as well so you might not need a full install to reproduce.
> > Sidenote : it boots fine on my intel-based laptop but crashes on my amd-based one.
> 
> What AMD GPU do you have?. If it's a recent one it may be missing firmware (hence X11 crashes/fails to start).

Ryzen 7 4700U with integrated Radeon RX Vega 7.

**Comment by AllanLinux** [comment]
Any news? Version nitrux-release-amd64_2021.06.29 I still get the error in Plymouth

**Comment by UriHerrera** [comment]
> Any news? Version nitrux-release-amd64_2021.06.29 I still get the error in Plymouth

_**It's not a Plymouth error**_. As I have mentioned in the replies above, the message will be displayed whether the splash is displayed or not, regardless of Plymouth's version. If the graphical session doesn't start it's because X11 is crashing or there's firmware missing for your graphics chip.

There's no console fallback because there's only a single TTY enabled by default.

**Comment by UriHerrera** [comment]
### Update

It seems that it may not even be related to X11 crashing specifically. Some people have mentioned that the default user session for them is not X11 but Wayland. Apparently, for some inexplicable reason, the Wayland session is set by default. Nonetheless, the issue is that the distribution doesn't start the graphical session (probably) due to missing GPU firmware.

To clarify why I say that it's not a Plymouth error, here's a GIF where the Plymouth theme is displayed, the graphical session starts, yet the error message is still printed to the console log.

![Peek 04-08-2021 14-48](https://user-images.githubusercontent.com/3053525/128245988-64884997-2c6f-4ca1-ad1a-a1b1091df3c6.gif)

**Comment by UriHerrera** [comment]
### Update

I've been able to add TTYs to the distribution (https://github.com/Nitrux/openrc-config/commit/642ec35d35cfbf129caea697aef7af55485d3712), so at least now there's a way to try to debug the problem when the graphical session doesn't start.

**Comment by derschneidertom** [comment]
the same error here on my system.
i have installed the version Nitrux 1.7.1 from USB (Ventoy) but after the reboot got the same error. "plymouth error failed for start".
my system: intel i5 10400f, 16gb, crucial nvme ssd 1tb.

I also have installed these OS with no Problems: Manajro, openSUSE KDE/Gnome, Win10pro/Win11pro. 
I do this for testing because i will change from windows to linux, but i will still game world of warcraft and some other games :-)

**Comment by UriHerrera** [comment]
> the same error here on my system. i have installed the version Nitrux 1.7.1 from USB (Ventoy) but after the reboot got the same error. "plymouth error failed for start". my system: intel i5 10400f, 16gb, crucial nvme ssd 1tb.
> 
> I also have installed these OS with no Problems: Manajro, openSUSE KDE/Gnome, Win10pro/Win11pro. I do this for testing because i will change from windows to linux, but i will still game world of warcraft and some other games :-)

Would you mind not adding _me too_ type of comments? Instead, add relevant information such as:

- Trying to start X11 with `startx` from a different TTY.
- Start a Wayland session using `startplasmacompositor` from a different TTY.
- Attach pictures or videos so that we know what's going on when you try to start a graphical session.

**Comment by derschneidertom** [comment]
sry i cannot make pictures or start anything, because i have deleted anything and use Win10 now.
but it is as i wrote. install from usb where anything is going fine, but after the first reboot to start the system live the error accures.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This comment is response to “http://github.com/Nitrux/nitrux-bug-tracker/issues/17#issuecomment-985932884”.

I am able to utilise the live image, but during subsequent boot from the local drive, immediately boot is ceased, with the most recent log being that invocation of Plymouth has failed. This is presented during initialisation of the live image, but it has not appeared to have affected the boot.

I am confident that it is because I have not installed drivers for my graphical processor since my most recent utilisation of Windows 11, which was some months before now.

**Comment by UriHerrera** [comment]
@BEEDELLROKEJULIANLOCKHART 

You mention the Live ISO works fine for you but not the installed system; I think that may be because X11 is not the default session, and Wayland is failing to initialize for you.

Switch to a different TTY using <kbd>Ctrl+Alt+F2</kbd> and run `startx` and post the outcome.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Because Maui Shell is incredible, I shall attempt to verify during the subsequent few days whether @UriHerrera's proposition shall allow me to invoke X11 via NitruxOS.

**Comment by Marcus-Arcadius** [comment]
![20220103_093312.jpg](https://user-images.githubusercontent.com/78793842/147891139-50714f9e-9445-44c6-aa11-4f3005a11f90.jpg)

Nitrux is unusable keep getting that plymouth error constantly but in the live iso it works.............

**Comment by Marcus-Arcadius** [comment]
![20220103_095308.jpg](https://user-images.githubusercontent.com/78793842/147891571-bcbbcd20-be88-4cab-b249-ece52f48a62b.jpg)

**Comment by UriHerrera** [comment]
> ![20220103_093312.jpg](https://user-images.githubusercontent.com/78793842/147891139-50714f9e-9445-44c6-aa11-4f3005a11f90.jpg)
> 
> Nitrux is unusable keep getting that plymouth error constantly but in the live iso it works.............

It is not the same error _and_ it's not a Plymouth error.

Did you install the distribution using BTRFS?.

**Comment by Marcus-Arcadius** [comment]
> > ![20220103_093312.jpg](https://user-images.githubusercontent.com/78793842/147891139-50714f9e-9445-44c6-aa11-4f3005a11f90.jpg)
> > 
> > Nitrux is unusable keep getting that plymouth error constantly but in the live iso it works.............
> 
> 
> @Marcus-Arcadius It is not the same error _and_ it's not a Plymouth error.
> 
> Did you install the distribution using BTRFS?.

I installed using the default that nitrux provides

**Comment by UriHerrera** [comment]
> > > ![20220103_093312.jpg](https://user-images.githubusercontent.com/78793842/147891139-50714f9e-9445-44c6-aa11-4f3005a11f90.jpg)
> > > Nitrux is unusable keep getting that plymouth error constantly but in the live iso it works.............
> > 
> > 
> > @Marcus-Arcadius It is not the same error _and_ it's not a Plymouth error.
> > Did you install the distribution using BTRFS?.
> 
> I installed using the default that nitrux providers
> 
> EDIT: I resolved the issue by doing a manually partitioning, and I've got to say Nitrux is the best looking Linux distro and probably the distro in which I will stay for a long time blush

I'm glad that you solved the problem; however, it's worth mentioning that the most recent ISO does not have this problem (also, this is off-topic here, there is already an issue about this). Please do not add off-topic comments; Github issues are not forum threads.

**Comment by drago26** [comment]
This also occurs for me on the live usb, of course I'm just bug testing. 

Minor Note: The software center when you're scrolling it glitches in and out.

**Comment by UriHerrera** [comment]
> This also occurs for me on the live usb, of course I'm just bug testing.
> 
> Minor Note: The software center when you're scrolling it glitches in and out.

@drago26 Do you mean that you see the error `ERROR: plymouth failed to start` when you boot the Live ISO? Or do you mean that the graphical session didn't start when you boot the Live ISO?.

**Comment by drago26** [comment]
> > This also occurs for me on the live usb, of course I'm just bug testing.
> > Minor Note: The software center when you're scrolling it glitches in and out.
> 
> @drago26 Do you mean that you see the error `ERROR: plymouth failed to start` when you boot the Live ISO? Or do you mean that the graphical session didn't start when you boot the Live ISO?.

Yeah I see the ERROR: plymouth failed to start.

- First it flickers and blacks out then comes back with the 3 dot loading screen which isn't aligned with the user's monitor one bit. Finally it boots into the graphical session with the KDE bug report application.
- Once you open the shop, and start to scroll it will flicker, and like bug out.

**Comment by UriHerrera** [comment]
@drago26 

- That's a weird thing that Plymouth does for some reason; if you boot the Live media again, it will show the Plymouth theme. My wild guess is that it's got something to do with the EFI NVRAM frame buffer. However, as I mentioned *numerous* times here, the system will print the error message because the error is not that Plymouth crashes or fails to start but the service script (otherwise, you wouldn't be able to see the default Plymouth theme, the three dots theme).

- Please report issues about the software center in the appropriate repository.

**Comment by ARNAVVGUPTAA** [comment]
Hey I encounter kind of the same problem here. The login manager works perfectely, but system doesn't seem to go beyond the splash screen. I can still login to tty from the splash screen too. This happened the first time I rebooted the system, because I have seen that actually helps with performance sometimes. Through tty, if I do startx then, the splash screen again appears, and I am still stuck at it. This time, black screen with only cursor. I have intel graphics.
![Uploading 5D132BEC-87A5-4FFB-89F2-C9B2897E42F7.jpeg…]()
![Uploading image.jpg…]()

**Comment by ARNAVVGUPTAA** [comment]
![B7E0B46D-E8E1-41EB-86E0-FCE31E7729BE](https://user-images.githubusercontent.com/62750957/155897854-fa33034a-cb5e-4b40-951c-f5d6e2661737.jpeg)

the animation doesn't complete

**Comment by ARNAVVGUPTAA** [comment]
And this is what I see when I press the power off key after I tty login
![6052E199-58F9-4E03-847E-33172896C9FF](https://user-images.githubusercontent.com/62750957/155897961-5b9a6b38-ee39-4a0b-9d30-84de37b49f15.jpeg)

**Comment by ARNAVVGUPTAA** [comment]
![image](https://user-images.githubusercontent.com/62750957/155898413-0cef5029-1950-4c91-88f9-eeb0409037b9.jpg)

**Comment by ARNAVVGUPTAA** [comment]
And the recovery mode is stuck here.
![image](https://user-images.githubusercontent.com/62750957/155926458-066187bf-33ae-4fbc-9580-4f86710c87fd.jpg)

**Comment by ARNAVVGUPTAA** [comment]
Hey guys! I solved it. Packages were being held back by the system and it included x11 packages which most likely introduced a bug. I updated those packes and am inside the most beautiful distribution I have ever seen!

**Comment by UriHerrera** [comment]
@ARNAVVGUPTAA Please do not add multiple comments; you can edit your original comment and add additional information. Also, the problem you're describing is entirely different from what is discussed here.

**Comment by UriHerrera** [comment]
> I can't seem to get past this problem the gui loads but it is just mouse nothing works really want to try this os but cannot even live boot any help will be immense

@anuppoudel54 Please add more information.

**Comment by rodan02** [comment]
> I know this is kind of an old issue but for the first time ever I encountered this problem with currently newest Nitrux 2.5.0 running in VirtualBox 7.0.0 from ISO file (I'm running Nitrux since v1.6.1). I was able to solve it by enabling 3D acceleration in VM display settings. I also used VMSVGA controller but it is possible that other controllers work fine, I just forgot to test them. Since one of the changes in Nitrux 2.5.0 were pre-installed NVIDIA drivers, maybe it has something to do with it. I'd just like to leave this note here for users who run Nitrux in VirtualBox, if that's okay with you. This thread is one of the top links when you search for plymouth failing to start.

This solution worked for me.Thanks.

**Comment by rokejulianlockhart** [comment]
@UriHerrera, doesn't that mean that Nitrux doesn't package the correct drivers, then? If other distributions work, that's Nitrux's fault, surely.

**Comment by UriHerrera** [comment]
@rokejulianlockhart  We do not develop, build or package the kernel; we **use it**; the Liquorix developer/maintainer does. And, of course, we do not develop, build or package the Nvidia proprietary driver nor do we develop, build or package MESA.

Suppose the version of the Liquorix kernel we include at any given release does not include any given firmware file for MESA drivers (AMD, Intel, or any VM adapter). That issue must be raised at its bug tracker.

Or, if the problem is __with MESA__, I think it's well known that we do not develop MESA and that any issues should be reported at their bug tracker.

We already include many __extra__ [firmware files](https://github.com/Nitrux/linux-firmware), including firmware for AMD and Intel.

Likewise, if Nvidia drops support for any given GPU architecture, that issue should be raised by the affected users to their support channels.

Just to let you know, we do mention this in the [Notes > Nvidia Proprietary Driver Information](https://nxos.org/notes/notes-nitrux-2-8-1/#nvidia-proprietary-driver-info).

> ⚠️ Important: The Nvidia proprietary driver cannot coexist with the Nouveau open-source driver user-space components; therefore, unsupported Nvidia GPUs cannot use this driver.

> ⚠️ Important: We cannot include any of the [Nvidia Legacy drivers](https://www.nvidia.com/en-us/drivers/unix/legacy-gpu/) (version 470, 390, etc.) alongside the current version, as Nvidia does not support installing two drivers simultaneously (see links [1](https://forums.developer.nvidia.com/t/setting-up-two-different-drivers-for-two-different-graphics-card/42252/24) and[ 2](https://forums.developer.nvidia.com/t/multiple-nvidia-drivers/34946/2)). Additionally, Nvidia drivers before version 470 (e.g., nvidia-390) do not support hardware-accelerated XWayland, causing non-Wayland-native applications to perform poorly in Wayland sessions.

I believe it's evident that since we're using Wayland now (since Nitrux 2.8.1) and Maui Shell is targeting Wayland, including the Nvidia Legacy drivers is not plausible.

Then, whatever changes Oracle or VMWare make to how their hypervisors use virtual graphics adapters are not our problem. There were issues regarding VirtualBox and Gnome Boxes not displaying the graphical session here; these issues are closed now because their respective developers seem to have fixed the problem.

Additionally, only two people provided details of their GPUs; in both cases, their problem wasn't related to missing firmware. 

My closing comment is due to various people commenting on Telegram using (unsupported) Nvidia graphics processors. The conclusion is that they don't have a problem with other distributions because other distributions use Nouveau by default instead of the proprietary driver. Thus, there's no graphical session if the driver is not providing firmware.

So, no, we disagree that it's our fault.

**Comment by kkmzero** [comment]
> @UriHerrera, doesn't that mean that Nitrux doesn't package the correct drivers, then? If other distributions work, that's Nitrux's fault, surely.

I work with a lot of distros and I encountered similar issue several times. For example, latest openSUSE Leap 15.5 with Plasma won't boot into login screen unless you have properly set graphics controller in VirtualBox. Not a big deal, just pick VMSVGA. So I can confirm, this is not issue only Nitrux has, at least in VBox, I had no problems on real HW with NVIDIA GPU.
