### ISSUE TITLE
SETUP

### ISSUE THREAD

**Issue by Tezza54** [Nitrux/nitrux-bug-tracker#172]
# Issue Description Trying to do setup in new PC

**Describe the bug**

Click on the  install, it opens up  when selecting language it  does  not  advance to next step
Please make sure to include a clear and concise description of what the bug is. 

**Steps to reproduce the bug**

4. See the error

**Expected behavior**

Could you describe what you expected to happen when the bug occurred?

**Screenshots**

Could you include screenshots to help explain your problem?

**Videos**

If images are not enough, include videos to help explain your problem.
 - GitHub doesn't support uploading videos, so please use video sharing like YouTube or Vimeo, etc., and include the URL.

**Additional context**

Please add any other context about the problem here, including what solutions you've tried already.

**OS version and Desktop information**

Nitrux 3.4.1

Open System Settings, go to About System, click "Copy to clipboard in English," and paste the content here.
 - If using System Settings is impossible, use `hw-probe` to provide this information.

**Hardware Information using hw-probe**

If the issue concerns hardware, use `hw-probe` (if it's not available, please download [hw-probe](https://linux-hardware.org/?view=howto)), run it using the following command 

```
sudo -E hw-probe -all -upload
```

And add the URL link.

# Logs

**Installation logs**

Please include the following log file for problems during the installation with Calamares. 

The file below is only available in the Live session.

- `~/.cache/calamares/session.log`

For problems regarding partitioning, run the command `sudo lsblk > lsblk.txt` and include the generated file.

**Boot logs**

Please include the following log files for problems with the distribution initialization process.

- `/var/log/rc.log`
- `/var/log/dmesg`
- `/var/log/boot.log`
- `/var/log/kern.log`

**System logs**

Include the following log file for problems with the distribution (overall).

- `/var/log/syslog`

**Desktop logs**

If you have problems with the graphical session, please include the following log file (generated by `desktop-config`) and the respective active session log file.
- `~/.desktop-config.log`

- For Plasma Wayland.
  - `~/.local/share/sddm/wayland-session.log`

- For Plasma X11.
  - `~/.local/share/sddm/xorg-session.log`

---

_*Disclaimer*: Please report issues to the appropriate developer(s). Nitrux is a Linux distribution that comprises dozens of free and open-source software projects._

**Comment by UriHerrera** [comment]
Please fill in the necessary information in the template. As is, there's nothing to reproduce your problem.
