### ISSUE TITLE
Networking during install/upgrade and unfinished upgrade/install

### ISSUE THREAD

**Issue by deeamboh** [Nitrux/nitrux-bug-tracker#175]
Yup, had a tough go at it for a while. Network was connected but couldn't ping anywhere. Was showing 103.2.3.5 or something similar on resolv.conf. I'm new to immutable root systems so took me too long to figure it out, plus the issue with editing anything on such a system. Anyway putting it out there so anyone goes thro this would probably get a clue.
Had to edit resolvconf.conf ( remove # from 127. ... .. ) then for good measure resolv.conf ( changed name server to my gateway).
Also install doesn't complete without error , third time now with different ISOs 
ERROR: Installation failed: "External command failed to finish"
looking thro calamares session log (don't know how to paste, sending this from my other laptop) , the log says 
Command <i>bash //bin/undebianize</i> failed to finish in 30 seconds.

looks like all dpkg and apt packages removed properly then update-grub then QProcess: Destroyed while process ("chroot") is still running. Skipping non-emergency job "Unmount file systems"
The system boots and works fine, just thought someone might wanna know.
Peace.

**Comment by UriHerrera** [comment]
The [tutorial to install the distribution](https://nxos.org/changelog/release-announcement-nitrux-3-5-0/) explicitly states the following:

> ⚠️ Important: The installation process requires mandatory active internet connectivity via wired or wireless connections. Please connect to a functional network before starting the installer.

> 🔰 Information: If you are already connected to the internet, your computer should be able to access [GitHub](https://github.com/) and the domain raw.githubusercontent.com.

> 🔰 Information: If your computer can reach [GitHub](https://github.com/) and the domain raw.githubusercontent.com, for example, using Firefox, adjust your computer’s time and date while using the Live session to avoid connectivity problems during installation. Run the following command to change the date and time using the terminal.

> Where MM means month, i.e., April is 04, DD means day, i.e., 30, hh, and mm means hour and minutes, i.e., 0207 for 02:57 AM, and YYyy is the year, i.e., 2024.

```
sudo date MMDDhhmmYYyy
```

> 🔰 Information: If your computer can’t reach either domain, you cannot proceed with the installation. We recommend using a VPN or a proxy or contacting your ISP if they block access to these domains. **_This is not a bug or issue with Nitrux or is caused by Nitrux._**
