### ISSUE TITLE
There's no internet connection despite connecting to a functional network

### ISSUE THREAD

**Issue by TalsanAlandor** [Nitrux/nitrux-bug-tracker#177]
Hi.

I just started the Live USB System. I have a normal LAN Cable to the Router. But the System has no internet. I dont know what to do.

**Comment by WJCPacketFence** [comment]
Same here.  I tried different networks.  Wired and wireless I get the same problem.  I verified the live version has my correct local time.

**Comment by UriHerrera** [comment]
Check the PSA: https://nxos.org/psa/psa-nitrux-3-5-0/

----

The issue has been fixed for the next release, https://github.com/Nitrux/nx-desktop-settings/commit/4d282f38476039f7813d805bd4c672d0b56ed85e
