### ISSUE TITLE
System Install failed with timeout error

### ISSUE THREAD

**Issue by hb8t** [Nitrux/nitrux-bug-tracker#180]
# Issue Description
Failed 3 times with the same error message. Dont remember the exact wording. Something like "command 'xxxx' to DeDebian (or   DeDebianize) failed after 30 seconds of wait.

**Comment by UriHerrera** [comment]
As mentioned in the [tutorial to install the distribution](https://nxos.org/tutorial/how-to-install-nitrux/#installing-nitrux):

> ⚠️ Important: The installation process requires mandatory active internet connectivity via wired or wireless connections. Please connect to a functional network before starting the installer. 

> ⚠️ Important: Note that devices such as laptops do not have any active network connection when booting, especially in the Live session since there are no saved and configured networks. Since Nitrux 3.5.0, we include NTPSec NTP to configure timezones; however, it requires connecting to an NTP server online. Additionally, if the time difference between your local time and the time on the device is over 6 hours, network servers will refuse connections. Other operating systems, including other Linux distributions, can alter the local time stored in your computer, which affects this time difference.

> 🔰 Information: If you are already connected to the internet, your computer should be able to access [GitHub](https://github.com/) and the domain raw.githubusercontent.com.

> 🔰 Information: If your computer can reach [GitHub](https://github.com/) and the domain raw.githubusercontent.com, for example, using Firefox, but can’t when using other methods such as the command ping, adjust your computer’s time and date while using the Live session to avoid connectivity problems during installation, either use the command date or right-click the clock in the top panel, select Adjust date and time, then click Timezone and search for your timezone, then click Apply.

> 🔰 Information: Run the following command to change the date and time using the terminal, where MM means month, i.e., April is 04, DD means day, i.e., 30, hh, and mm means hour and minutes, i.e., 0207 for 02:57 AM, and YYyy is the year, i.e., 2024.

```
sudo date MMDDhhmmYYyy
```

> 🔰 Information: For problems with Calamares during installation, include ~/.cache/calamares/session.log in a bug report. Please note this file is only available during the live session.

----

_**Please use the right template to report bugs, since this issue doesn't have useful information._

**Comment by hb8t** [comment]
The error I quoted talks nothing about lack of internet connection. I encountered the error after around 90 percent of the install process. Which means the internet check has been passed.

**Comment by UriHerrera** [comment]
That error could've occurred for any number of reasons. It could've happened because your computer queried raw.githubusercontent.com for the script and the server refused the connection, possibly due to certification validation failing. It could've been that generating the GRUB menu took longer than 30 seconds.

However, we don't know that because there's no concrete information whatsoever in your issue. I'd prefer not to be guessing the problem. So, follow the instructions in the installation tutorial quoted above, and update your issue with concise information using the bug report template.

**Comment by hb8t** [comment]
Is it possible to tell the installer to use http rather than https for all its raw.githubusercontent.com queries during the install?

**Comment by UriHerrera** [comment]
> Is it possible to tell the installer to use http rather than https for all its raw.githubusercontent.com queries during the install?

Yes, you can edit the module configuration. The tutorial mentions how to do that.

> ⚠️ Important: We do not recommend skipping certificate checks due to the potential security risks. We strongly emphasize that users should adjust the time correctly before considering this option. For instructions, please see below. However, the commands below will tell Calamares to bypass certificate verification when downloading these files as part of the installation process. Only use this option if you are certain of the site’s authenticity or, if you do not care about the validity of its certificate. It is always a bad idea not to check certificates when transmitting confidential or important data. Proceed at your own risk!

```
sudo sed -i '/wget /s/wget /wget --no-check-certificate /' /etc/calamares/modules/shellprocess_nx-SP#01linker.conf
sudo sed -i '/wget /s/wget /wget --no-check-certificate /' /etc/calamares/modules/shellprocess_nx-SP#02rdpkg.conf
```

**Comment by maheshp1999** [comment]
I got similar error today while trying installation.
Did you find any solution? please share. 
this happened in 2nd last stage of installation very disheartening.

**Comment by hb8t** [comment]
It did not work again. BTW, i am from a location where raw.githubusercontent.com needs a VPN to be reached on Windows. I dont have any way to achive that and certainly wont go to the step of installing a VPN on my live installer USB..

Let me know if you can give alternative guidance or suggest additional help.

**Comment by UriHerrera** [comment]
> It did not work again. BTW, i am from a location where raw.githubusercontent.com needs a VPN to be reached on Windows. I dont have any way to achive that and certainly wont go to the step of installing a VPN on my live installer USB..
> 
> Let me know if you can give alternative guidance or suggest additional help.

I'm sorry, but the ISPs blocking the domain are out of what we can help with. We can only recommend using VPNs or talking to their support.
