### ISSUE TITLE
Unable to boot Nitrus Usb created from .iso file

### ISSUE THREAD

**Issue by jddavidm** [Nitrux/nitrux-bug-tracker#184]
# Feature Request

**Is your proposal related to a problem?**

I downloaded the .iso file which I loaded on a USB drive using Rufus, but I got the message that the boot USB is UEFI based, and it wouldn't boot if my PC is BIOS based (an old Dell 531 desktop BTW) and indeed the boot process simply hung

**Describe the solution you'd like**

Include the BIOS option in the .iso file

**Describe alternatives you've considered**

(Write your answer here.)

**Additional context**

(Write your answer here.)

---

_*Disclaimer*: Please do not create feature requests for software that Nitrux does not develop._

**Comment by UriHerrera** [comment]
The ISO does support Legacy BIOS. Select the appropriate option in Rufus and read the [installation tutorial](https://nxos.org/tutorial/how-to-install-nitrux/#flash-iso-with-rufus).
