### ISSUE TITLE
Add support for LVM2 volumes

### ISSUE THREAD

**Issue by Enkouyami** [Nitrux/nitrux-bug-tracker#189]
# lvm2 package is missing

On Nitrux, none of the `lvm2`  commands are recognized.

Also, the Calamares installer, shows that there are logical volumes, but cannot do anything with them.

**Comment by UriHerrera** [comment]
Added for next release https://github.com/Nitrux/nx-desktop-apps/commit/11fa1e502272e14c3bcbc106aa0e50cf79ea0e76
