### ISSUE TITLE
Following initial install and after each reboot Primary user's directory must be created in /home.

### ISSUE THREAD

**Issue by OZZY-The-Wiz** [Nitrux/nitrux-bug-tracker#190]
Primary User's directory & all contents are removed on power down/reboot.  Attempts to login fail.  Must recreate user's directory and reinstall apps on every reboot.

**Comment by UriHerrera** [comment]
Please read the [installation tutorial](https://nxos.org/tutorial/how-to-install-nitrux/#installing-nitrux), which is available on the website or offline in the Documentation directory on the desktop.

> ⚠️ Important:  Please be aware that the root directory is immutable, and any directory within the root will be read-only. Do not use a single partition layout.

**Comment by OZZY-The-Wiz** [comment]
Thank you.  Sorry for the inconvenience.  I will check out and re-try your default installation process.
