### ISSUE TITLE
Move to Wayland

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nitrux-bug-tracker#20]
We all know X11 is old, jolly, and stable, but Wayland is set to be the next standard for display servers in Linux, at least.

Currently, we do not ship anything related to Wayland. So, here's a list of what we should look to.

- [x] Have a Wayland session.
- [x] Working on a Wayland-enabled desktop.
- [ ] Outside of Waylands' issues, no showstopping bugs.

**Comment by ryanrms** [comment]
Is the information in the above "Status Update" still current?  I installed using the latest ISO, and the three options available to me are Cask (Wayland), Cask (X11), and Plasma (X11).  Both versions of the Cask session fail to show on both my monitors (only on HDMI-A-0 and not on DVI-D-0), additionally the Wayland session of Cask doesn't recognise my mouse.

**Comment by UriHerrera** [comment]
## Status Update #2

Like in 2021, the Plasma Wayland session works _if you're using MESA drivers_, so only Nouveau, AMDGPU, i945, etc., will work properly. Either way, the Nvidia proprietary driver *still does not work with Plasma Wayland*.

There is an open-source (kind of) Nvidia driver. However, I know it only supports some professional cards and no consumer cards, so it does not help resolve the issue, even if we include Plasma Wayland or other Wayland sessions (like Maui Shell).
