### ISSUE TITLE
NX internationalization

### ISSUE THREAD

**Issue by pYFZOS5** [Nitrux/nitrux-bug-tracker#21]
Does nitrux has own localization procedure or take them from upstream? i couldn't find details on website.

**Comment by UriHerrera** [comment]
Which parts of the distribution are you referring to (about localization)?.

KDE and Plasma include their own translation files. Other programs use translation files in `/usr/share/locale-langpack/`[LANG]`.

If you are referring to Maui Apps, no, they do not include translations.

**Comment by pYFZOS5** [comment]
Then it seems nitrux doesn't require special localization. Past i asked from telegram group but wasn't aware well about that, i am going to close this issue
