### ISSUE TITLE
Cannot create a user called nitrux when installing from Nitrux live image

### ISSUE THREAD

**Issue by Chaz6** [Nitrux/nitrux-bug-tracker#23]
**Describe the bug**
When installing Nitrux, I want to create a user called `nitrux` but when I try an error is displayed.

**To Reproduce**
1. Boot from the latest Nitrux live image
2. Complete all the required configuration
3. When prompted for a user to create, enter `nitrux`

**Expected behavior**
A user `nitrux` should be created on the target system.

**Screenshots**
![image](https://user-images.githubusercontent.com/12680/113110139-a58af480-91fe-11eb-9036-f9b64b88a43e.png)

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by UriHerrera** [comment]
Fixed in https://github.com/Nitrux/iso-tool/commit/a2a2989f0ef2be7b66c77db2b29c13821c67d24b
