### ISSUE TITLE
Graphical Shutdown and Restart buttons do not function

### ISSUE THREAD

**Issue by Sarcasmo220** [Nitrux/nitrux-bug-tracker#24]
**Describe the bug**
Graphical shutdown and restart dialog buttons do not shutdown or restart the system

**To Reproduce**
1. Open up Ditto application menu
2. Click on shutdown icon
3. Click on shutdown option in dialog window that shows different leave options
4. User is logged out instead of system shutting down

**Similar Bug**
In login screen, graphical shutdown or restart buttons do not shutdown or restart system

**Steps**
1. Boot up system
2. At login screen, click on shutdown or restart button
3. Nothing happens

**Expected behavior**
System shuts down or restarts

**Desktop (please complete the following information):**
 - OS: Nitrux
 - Version 1.3.9 build.260321
 - CPU: Intel i7 6500U

**Comment by UriHerrera** [comment]
Plasma seems to have changed the command that it uses to shut down or restart, and it's not using `/usr/sbin/poweroff` or `/usr/sbin/reboot`.

---

@pierroute Please don't add  _me too_ comments.

**Comment by UriHerrera** [comment]
Bug fixed in https://github.com/Nitrux/openrc-config/commit/48c3e6d2188a2c174a63d8008ec41544984e4667

---
