### ISSUE TITLE
Boot Nitrux ISO via grub loopback function don’t work.

### ISSUE THREAD

**Issue by Mexit** [Nitrux/nitrux-bug-tracker#25]
**Describe the bug**

We have a loopback.cfg file on the ISO image. It loads the configuration from the grub.cfg file. Unfortunately, it does not contain the variables needed to boot the system - Nitrux does not boot.

**To Reproduce**

Boot image by [MultiOS-USB](https://github.com/Mexit/MultiOS-USB) or create GRUB menu manually.

**Expected behavior**

System start-up.

**Desktop (please complete the following information):**

 - nitrux-release-amd64_2021.05.01.iso
 - nitrux-release-minimal-amd64_2021.05.01.iso

**Fix**

Please add `iso-scan/filename=$iso_path` to kernel parameters in grub.cfg.

**Comment by UriHerrera** [comment]
I've built a new ISO that includes this change; here's the URL https://repo.nxos.org/iso/nitrux-release-amd64_2021.05.10.iso.

**Comment by RaptaG** [comment]
This has been stale for 2 years, I believe it's an important issue. In fact it's the one preventing me from installing Nitrux. Are there any updates on this? The change is very simple to add. Please let me know if there are any updates..

**Comment by UriHerrera** [comment]
> This has been stale for 2 years, I believe it's an important issue. In fact it's the one preventing me from installing Nitrux. Are there any updates on this? The change is very simple to add. Please let me know if there are any updates..

 The change mentioned in this issue is already available in the ISO. The parameter `iso-scan/filename=$iso_path` was added over two years ago.

**Comment by RaptaG** [comment]
> > This has been stale for 2 years, I believe it's an important issue. In fact it's the one preventing me from installing Nitrux. Are there any updates on this? The change is very simple to add. Please let me know if there are any updates..
> 
> @RaptaG   The change mentioned in this issue is already available in the ISO. The parameter `iso-scan/filename=$iso_path` was added over two years ago.
> 
> 

I get a similar issue with Ventoy though.

**Comment by RaptaG** [comment]
I can't boot into the .iso

**Comment by RaptaG** [comment]
@UriHerrera

**Comment by UriHerrera** [comment]
@RaptaG  You can edit your comments; please don't spam. If you have an issue booting the ISO, you can open a new issue with your specific problem.
