### ISSUE TITLE
Can't install anything related of appimage.

### ISSUE THREAD

**Issue by Noobao** [Nitrux/nitrux-bug-tracker#27]
Software center is also broken as well,i suspect it may be a issue related to FUSE.

The applications i tried to install were Appimage First Run Utility and librewolf.

sudo modprobe fuse does not detect anything wrong.

"there was an error while trying to execute appimage"

**Comment by UriHerrera** [comment]
Which software center are you referring to? Plasma Discover? or our software center? The AppImage and code in the master branch of our software center  __does not__ work. If you want to test our software center use the branch `dev-mauikit-ui`.

You don't need to force-load the FUSE module to get AppImages to work in the distribution. They will work. Also, you don't need to add any extra software to integrate them, that will happen automatically.

We already include AppImages by default, like Inkscape which run fine.

![VirtualBox_Nitrux (legacy)_13_05_2021_18_39_24](https://user-images.githubusercontent.com/3053525/118200495-cd36c480-b41a-11eb-8c6e-94e15209de1a.png)

I went ahead and downloaded Librewolf, and then just moved it to the Applications directory.

![VirtualBox_Nitrux (legacy)_13_05_2021_18_44_33](https://user-images.githubusercontent.com/3053525/118200696-5c43dc80-b41b-11eb-8326-e6e80e1e89f1.png)

As you can see I didn't have to do anything else, the application appears in the menu and launches without a problem.

![VirtualBox_Nitrux (legacy)_13_05_2021_18_44_48](https://user-images.githubusercontent.com/3053525/118200698-5cdc7300-b41b-11eb-8385-b904c810a877.png)
