### ISSUE TITLE
Default Latte layout corrupted after installation in Nitrux 1.6

### ISSUE THREAD

**Issue by kanwarplaha** [Nitrux/nitrux-bug-tracker#28]
Hi,
First of all, I was super excited to download release 1.6. The live boot desktop looked awesome. However, on installing it to HDD, here is what I noticed:
- No top panel
- Only Firefox and the clock on the bottom panel
- On upgrading the system (apt-get upgrade), it lists about 500 packages that is says are ready to be removed!

I downloaded and installed the "standard" edition of the ISO. 

Looking forward to resolving this as I do want to use Nitrux as my go-to desktop :)

Please help.

**Comment by UriHerrera** [comment]
At random, there's a possibility that the default Latte layout (nx-top-panel2) is corrupted when booting for the first time after the installation is completed. As a result, a 'Default' Latte layout is created and used.  To fix this, run the following command.

`cp -r /etc/skel/.config/latte/nx-top-panel-2.layout.latte ~/.config/latte/nx-top-panel-2.layout.latte`

Log out and log in.

**Comment by UriHerrera** [comment]
> Hi @UriHerrera , thanks heaps for your detailed replies with screenshots.
> 
> Can I ask which ISO I should be downloading? I had used the links on https://nxos.org/changelog/release-announcement-nitrux-1-6-0#download page.
> 
> Could you please point me to the right one?
> 
> Thanks.

All the download links in the announcement are correct.

**Comment by kanwarplaha** [comment]
Yes, confirmed that the download file and the MD5 checksum is correct. Still the same issue on reinstall. Posting this here as I am also sharing the details with you on the telegram channel :)

**Comment by kanwarplaha** [comment]
> At random, there's a possibility that the default Latte layout (nx-top-panel-2) is corrupted when booting for the first time after the installation is completed. As a result, a 'Default' Latte layout is created and used.  To fix this, run the following command.
> 
> `cp -r /etc/skel/.config/latte/nx-top-panel-2.layout.latte ~/.config/latte/nx-top-panel-2.layout.latte`
> 
> Log out and log in.
> 
> Then select the Latte layout from its right-click menu.
> 
Okay, that worked for the latte panels. Now, for the station startup error where it does not set the zsh theme correctly. Is there another config file missing that I should copy to my $HOME? Thanks.

**Comment by UriHerrera** [comment]
> > At random, there's a possibility that the default Latte layout (nx-top-panel-2) is corrupted when booting for the first time after the installation is completed. As a result, a 'Default' Latte layout is created and used.  To fix this, run the following command.
> > `cp -r /etc/skel/.config/latte/nx-top-panel-2.layout.latte ~/.config/latte/nx-top-panel-2.layout.latte`
> > Log out and log in.
> > Then select the Latte layout from its right-click menu.
> 
> Okay, that worked for the latte panels. Now, for the station startup error where it does not set the zsh theme correctly. Is there another config file missing that I should copy to my $HOME? Thanks.

Add another issue for the missing ZSH configuration and mention this issue, so the issues aren't mixed.

**Comment by UriHerrera** [comment]
The issue seems to have gone away in newer versions of Latte.
