### ISSUE TITLE
znx: Error: Bad image name (must match '^[a-zA-Z0-9_]+/[a-zA-Z0-9_]+$').

### ISSUE THREAD

**Issue by goshawk22** [Nitrux/nitrux-bug-tracker#3]
I just downloaded nitrux.iso
When I run the command sudo ./znx deploy /dev/sda nitrux/$version nitrux-stable-amd64.iso
it gives the error znx: Error: Bad image name (must match '^[a-zA-Z0-9_]+/[a-zA-Z0-9_]+$').

Thank you,
From Adam

**Comment by UriHerrera** [comment]
Please check https://nxos.org/en/faq/#i-deployed-nitrux-using-znx-but-i-got-an-error.

**Comment by goshawk22** [comment]
Thank you. I'm a bit new, sorry.
