### ISSUE TITLE
When creating a user in Calamares named "nitrux" the .cache directory in the user's home has the wrong ownership

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nitrux-bug-tracker#33]
**Describe the bug**
When creating a user in Calamares named "nitrux" the .cache directory in the user's home has the wrong ownership, and as a result, no applications are listed in the dock or the app menu. 

**To Reproduce**
1. Install Nitrux.
2. Create a user during the installation with username `nitrux`.
3. Boot to the installation.
4. No app icons in the dock or the app menu. Also affects other programs.

**Expected behavior**
Application icons in dock and app menu.

**Screenshots**
![VirtualBox_Nitrux_02_09_2021_20_55_38](https://user-images.githubusercontent.com/3053525/131939249-f04bcaa7-f5c3-46a4-8c73-4664f85dce04.png)

![VirtualBox_Nitrux_02_09_2021_20_59_21](https://user-images.githubusercontent.com/3053525/131939331-f0ab2eb9-8484-43b7-a630-b4c1242eed25.png)

**Desktop (please complete the following information):**
 - Nitrux (=> 1.6.0+

**Additional context**
To fix this, run the following command.

`sudo chown nitrux:nitrux ~/.cache`

**Comment by adriaandegroot** [comment]
You could patch *src/modules/users/Config.cpp* function `Config::forbiddenLoginNames()` to forbid *nitrux* as a username, to avoid this problem. That doesn't sound like a great idea, though: it arbitrarily denies one special name.

Better is to figure out what / why the `.cache` directory is being created in the target system with the wrong UID attached -- presumably the UID of the live user in the ISO, which is **numerically** different from the UID of the named user in the target system.

**Comment by UriHerrera** [comment]
Issue is no longer present in version Calamares 3.2.49.1.
