### ISSUE TITLE
Cannot resize windows from corners

### ISSUE THREAD

**Issue by AwesomeKenP** [Nitrux/nitrux-bug-tracker#35]
**Describe the bug**
After installing 1.6.0, I have noticed that I cannot resize windows from corners. Only horizontal and vertical resizing works.

**To Reproduce**
1. Open up any app window, such as Station or Index or a browser
2. Use the mouse to try and resize the window from, say, bottom-right corner

**Expected behavior**
The cursor changes shape and the window can be resized. _Note the mouse pointer in the attached screenshot below._

**Screenshots**
![NitruxBug](https://user-images.githubusercontent.com/37039351/133182024-ad8280d2-9ecf-4a39-9749-3b5af058b791.png)

**Desktop (please complete the following information):**
 - OS: Nitrux
 - Browser (N/A)
 - Version: 1.6.0

**Additional context**
None.

**Comment by UriHerrera** [comment]
I've tried to duplicate this problem on VirtualBox and my computers, and it looks like it's a problem with the cursor theme. You _can_ resize the window if you put the cursor in the corner, but it doesn't change to the correct cursor image.

So, this is a bug in https://github.com/nx-desktop/nx-plasma-look-and-feel

**Comment by UriHerrera** [comment]
Fixed in https://github.com/nx-desktop/nx-plasma-look-and-feel/commit/65cdc3a8515a83af9c190bb61b4658896cfb1ad3

**Comment by kanwarplaha** [comment]
Nice one @UriHerrera ! I'll give it a go. Cheers.
