### ISSUE TITLE
Move to PipeWire

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nitrux-bug-tracker#37]
We all know PulseAudio _exists_, but PipeWire is set to be the next standard for audio servers in Linux, at least.

Currently, we do ship with PipeWire, but it's not configured to replace PulseAudio. So, here's a list of what we should look to.

- [ ] Replace PulseAudio with PipeWire as audio server.
- [ ] Add PipeWire service for OpenRC.

**Comment by fatalerrors80** [comment]
I moved to PipeWire, and it's working great, even less issue than with PulseAudio despite the youth of the project. But on the emerge side, I have several dependency issues. Several packages wants PulseAudio even if PipeWire SDK should take it in charge and Pulse would be no longer required.

Also, the alsa-plugins and gst-plugins-jack package are real blockers both pulling the Jack2 server which conflicts with PipeWire. Thus I just can't upgrade system normaly.

**Comment by UriHerrera** [comment]
Nitrux 2.6.0 includes PipeWire, specifically, Pulseaudio on Pipewire.
