### ISSUE TITLE
After installation, SDDM automatically selects any Wayland session (if available) even if it's not the default

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nitrux-bug-tracker#39]
Apparently, for some users, after installing the distribution, the Plasma Wayland session is the default session instead of the Plasma X11 session. This problem has led some users to (incorrectly) determine that there's a problem with Plymouth as described in #17 as the last message printed to the boot log is `ERROR: plymouth failed to start`, which in itself isn't a problem _with_ Plymouth as I've repeatedly mentioned there.

These users have mentioned that they can boot the ISO without problems, and this is because the ISO does use X11 as the default session as we have set this configuration in the login manager configuration file in `/etc/sddm.conf` and `/etc/sddm.conf.d/kde_settings.conf`,

```
[General]
EnableHiDPI=true
InputMethod=
```

```
[Autologin]
Relogin=false
Session=plasma
User=

[General]
HaltCommand=/usr/sbin/poweroff
RebootCommand=/usr/sbin/reboot

[Theme]
Current=nitrux-dark
CursorTheme=nitrux_snow_cursors

[Users]
MaximumUid=60000
MinimumUid=1000
```

The key `Session=` value should be either the name of an X11 session or a Wayland session. In this case, the value is `plasma`, which is the Plasma X11 session, and the name of the Plasma Wayland session is `plasmawayland`.

When the Calamares installer performs the decompression and extraction of the SquashFS file to the target device creating the root directory, these files should remain identical except for the value of the key `User=`, which should have the username of the user.

The reasons for this behavior are unknown, and I'm unable to reproduce this issue on my computers.

**Comment by ryanrms** [comment]
I installed and on this system the configuaration seems to be stored in /etc/sddm.conf.d/kde_settings.conf
Note the small difference "sddm.d" vs "sddm.conf.d", maybe this is useful, maybe not.

**Comment by UriHerrera** [comment]
#### Update

Removing the Plasma (Wayland) session did not resolve the problem as SDDM _forcefully_ loads *any* Wayland session, notably on *some* computers but not in others. The reasons for this are **incomprehensible** as we *do not* set the Cask (Wayland) session as the default graphical session (for obvious reasons) as Maui Shell is in _development_ and it doesn't work correctly.

As I mentioned above, the ISO boots to X11 because that's what we're telling SDDM to do with our configuration file. So it makes no sense to me why SDDM forces the Wayland session **after** the distribution is installed.

**Comment by rmnscnce** [comment]
Since version [0.19.0](https://github.com/sddm/sddm/releases/tag/v0.19.0), SDDM now automatically [prefers Wayland over X11 sessions](https://github.com/sddm/sddm/commit/994fa67b01ccfac1aaac08572302bbbea7842dc3).

To disable this behavior you can ship the `/etc/sddm.conf` to include `Autologin::Session=plasma.desktop` in the file for installation:
```ini
[Autologin]
Session=plasma.desktop
```

**Comment by rmnscnce** [comment]
For reference, this is how it's applied in the Nitrux 2.0.0 build.280122 live media:
![image](https://user-images.githubusercontent.com/31619874/152717877-8ea2d82f-645f-4728-ba05-63c3d6f46df0.png)

And in a fresh installation of Nitrux 2.0.0 build.280122:
![image](https://user-images.githubusercontent.com/31619874/152718501-21a531d8-fc93-4697-8214-1096741d6a40.png)

If this is unexpected, you may want to fix the ISO build scripts to include the correct /etc/sddm.conf for the installation image and possibly fix the issue.

Alternatively — for modularity, you can make `/etc/sddm.conf.d/nitrux-prefer-plasma-x11.conf` with `Autologin::Session=plasma.desktop` and package it into a DEB to be pre-installed.

**Comment by nealbrophy** [comment]
I can confirm that it defaults to "Cask (Wayland)" on fresh installs on my Slimbook ProX15. Let me know if you need additional info.
[system_info.txt](https://github.com/Nitrux/nitrux-bug-tracker/files/8050011/system_info.txt)

**Comment by UriHerrera** [comment]
The latest ISO [nitrux-release-amd64_2022.02.28.iso](https://updates.nxos.org/nitrux-release-amd64_2022.02.28.iso) includes a prior version of SDDM that does not default to Wayland sessions.

Until we patch SDDM to prefer X11 sessions or wait for an update of SDDM to respect its configuration file, that will be the case.
