### ISSUE TITLE
ISO doesn't boot on Mac

### ISSUE THREAD

**Issue by gerd35** [Nitrux/nitrux-bug-tracker#43]
**Describe the bug**
I tried various ways of creating a bootable USB in macOS (balena Etcher, ROSA Image Writer, dd) but every time I try to boot from it, only the default macOS drive is shown as boot option.

**To Reproduce**
1. Download latest (desktop) ISO
2. Flash it to a USB drive in macOS
3. Try to boot from it on macOS machine
4. USB drive does not appear as boot option.

**Expected behavior**
Booting into a live Nitrux system.

**Desktop (please complete the following information):**
 - OS : macOS Big Sur (11.5.2)

**Additional context**
Other Linux ISOs boot just fine.

**Comment by UriHerrera** [comment]
Can you add the output of `dd` and `diskutil list`? Also, please make sure that the checksum of the ISO matches the MD5 files.

**Comment by gerd35** [comment]
I have checked the checksums, they match. Also I just realised that the drive won't show in macOS anymore. After I changed ports it suddenly worked and I was able to capture this `diskutil list` output:

> /dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *121.3 GB   disk0
   1:                 Apple_APFS ⁨Container disk1⁩         121.1 GB   disk0s2

>/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +121.1 GB   disk1
                                 Physical Store disk0s2
   1:                APFS Volume ⁨Macintosh HD - Data⁩     91.8 GB    disk1s1
   2:                APFS Volume ⁨Preboot⁩                 591.1 MB   disk1s2
   3:                APFS Volume ⁨Recovery⁩                626.4 MB   disk1s3
   4:                APFS Volume ⁨VM⁩                      2.1 GB     disk1s4
   5:                APFS Volume ⁨Macintosh HD⁩            22.3 GB    disk1s5
   6:              APFS Snapshot ⁨com.apple.os.update-...⁩ 22.3 GB    disk1s5s1

>/dev/disk2 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *30.8 GB    disk2
   1:                       0xEF ⁨⁩                        1.6 MB     disk2s2
                    (free space)                         27.5 GB 

Seems to me as if the EFI executable is in the wrong spot. Afterwards I removed the drive again (for some reason I can't remember) and I haven't been able to get it to show again ever since, so I can't post the output of a second `dd` run unfortunately. From what I remember from the first one though it just said something like "sucessfully transfered xy bytes from ISO to /dev/disk2".

**Comment by kanwarplaha** [comment]
same behaviour observed as @gerd35 i.e. the USB disk not showing in boot options menu (2014 Macbook  Pro).

**Comment by kanwarplaha** [comment]
Confirmed that the ISO does not boot on Mac. 
- The USB key appears as "Windows" disk in the boot options menu.
- After selecting it from boot options menu, the following message is displayed after a few seconds:
`No bootable device -- insert boot disk and press any key`

**Comment by UriHerrera** [comment]
Fixed in https://github.com/Nitrux/tools/commit/7a84e35c6856593e54cad3eaa6a4373e9e4cd51d

**Comment by kanwarplaha** [comment]
@UriHerrera, just documenting the steps that got it to work:
1. Mounted the ISO to a temp location
`sudo mount -o loop nitrux-release-amd64_2022.01.19.iso /media`
2. `cd /media`
3. `xorriso -as mkisofs -iso-level 3 -full-iso9660-filenames -volid "Repack" -eltorito-alt-boot -no-emul-boot -e efi.img -graft-points efi.img=efi.img -append_partition 1 0xef efi.img -o /root/niturx_for_mac.iso`
**NOTE: I used partition 1 rather than partition 2**
4. `sudo dd if=/root/nitrux_for_mac.iso of=/dev/sdb oflag=sync bs=4M status=progress`
This showed the disk as "EFI Boot" on the Mac boot options and then the live CD booted normally.
