### ISSUE TITLE
Next button is disable in users section while installing

### ISSUE THREAD

**Issue by AliAkbari97** [Nitrux/nitrux-bug-tracker#45]
Next button in users section while installing is inactive

I can't continue installing nitrux 
I have this problem with version 1.8

**Comment by UriHerrera** [comment]
@AliAkbari97 Are you referring to the Calamares installer? Have you filled the required fields for username, user password, and root password?.

**Comment by AliAkbari97** [comment]
Yes I have this problem with calamares installer & I filled all required feilds...
At last I download and install pervious release
But I found new bug!
The store didn't work. Pc was connected to the internet & web browsing was trouble-free...
I have this issue with live version of latest release too

**Comment by UriHerrera** [comment]
@AliAkbari97 Please add media where these problems are visible; I can't reproduce them.

**Comment by Hikotiko** [comment]
I had the same issue couldn't understand why, but your passwords needs to be at least 8 and needs to have a special character, number, capital and possibly a small letter.

**Comment by Hikotiko** [comment]
> Next button in users section while installing is inactive
> 
> I can't continue installing nitrux I have this problem with version 1.8

I had the same issue couldn't understand why, but your passwords needs to be at least 8 and needs to have a special character, number, capital and possibly a small letter.

**Comment by UriHerrera** [comment]
> I had the same issue couldn't understand why, but your passwords needs to have at least 8 and needs to have a special character, number, capital and possibly a small letter.

@Hikotiko The problem discussed in this issue is unrelated to the newly added password policy in the Calamares installer.
