### ISSUE TITLE
Dolphin cannot run/open Appimage files

### ISSUE THREAD

**Issue by kanwarplaha** [Nitrux/nitrux-bug-tracker#50]
**Describe the bug**
In 1.8.0 Dolphin could open/run Appimage files. In 2.0.0 this does not work.

**To Reproduce**
1. Open Dolphin
2. Browse to a folder that contains Appimages
2. Click on any one of the Appimages
3. A dialog box opens asking to open the file with

**Expected behavior**
When clicked, an Appimage should run/open from Dolphin

**Screenshots**
![Screenshot_20220201_210646](https://user-images.githubusercontent.com/62160679/151949266-caa9424b-e280-4ec2-9ee7-179ad97b4e61.png)

**Desktop (please complete the following information):**
 - OS: Nitrux Linux
 - Browser: (N/A)
 - Version: 2.0.0

**Comment by UriHerrera** [comment]
I installed Dolphin 21.12.3, browsed a folder with AppImages, and once I clicked on a file, I got this dialog.

![image_2022-04-01_22-50-34](https://user-images.githubusercontent.com/3053525/161366818-969f93ba-f4f7-46ff-a052-bd8c84090dd1.png)

Clicking <kbd>Execute</kbd> runs the AppImage.
