### ISSUE TITLE
My iPad isn’t getting detected.

### ISSUE THREAD

**Issue by aclosetweeb** [Nitrux/nitrux-bug-tracker#56]

**Comment by UriHerrera** [comment]
Please add more information; I have no idea what your problem is.

**Comment by aclosetweeb** [comment]
My apologies for not describing it properly.

I can’t access or sync my iPad from my computer which runs Nitrux.

**Comment by UriHerrera** [comment]
We have added the necessary software to access iDevices in the distribution; however, currently, iDevices have to be mounted manually. If you find this an issue, please create a separate one.

1. Open a terminal and type.

```
sudo usbmuxd -f -v &
```

2. Connect your iPad, unlock it and tap 'Trust' when the message "Trust this device" appears.

Now, depending on what you want to do, you can use `ifuse`, a fuse filesystem, to access the contents of iOS devices.

If you only want to access the Media folder on the device, do the following.

Create a mount-point for the Media folder on the device.

```
sudo mkdir /media/ipad-Media
```

And then, do the following.

```
ifuse /media/ipad-Media
```

----

`ifuse` can also mount areas of the iPad by AppID, which allows the user to transfer files, which the particular application may then use. The AppID is [a kind of namespace](http://stackoverflow.com/questions/555424/what-is-the-app-id-that-the-apple-developer-connection-site-is-asking-me-for), particular to each application.

#### Mount by AppID:

List the AppIDs of the Apps currently installed on your device.

```
ideviceinstaller -l
```

Then mount the app.

```
ifuse --appid com.apple.iBooks /media/ipad-com.apple.iBooks
```

If you get the error "bad mount point," try this command instead previous:

```
ifuse --documents com.apple.iBooks /media/ipad-com.apple.iBooks
```

Now you are free to copy files to the mounted folder, which will be accessible to that app (iBooks in this example).
