### ISSUE TITLE
Cannot install software-properties-common

### ISSUE THREAD

**Issue by ARNAVVGUPTAA** [Nitrux/nitrux-bug-tracker#57]
Hey! So i can't install software-properties-common package as I need it to add apt repositories. I don't think it's a bug, but I was hoping you could help me with this.
![image](https://user-images.githubusercontent.com/62750957/156923141-88369c79-e8d9-41da-93c2-c9c5e939ef01.png)

**Comment by UriHerrera** [comment]
First, you *can* install it. We mention *how* as well on our tutorial to install other desktop environments.

`sudo apt install software-properties-common/unstable`  

Second, you **do not need it** to add APT repositories at all. By the looks of it what you want to add is a PPA, which you can add manually following the instructions on the PPA itself.
