### ISSUE TITLE
kayboard template is missing for a standard Lenovo qwertz w500

### ISSUE THREAD

**Issue by renato46** [Nitrux/nitrux-bug-tracker#58]
**Describe the bug**
first time to install Nitrux (2.0.1) on a test laptop in order to evaluate it
In the repository is not present the keyboard of my Lenovo W500 that has a german qwertz layout

**To Reproduce**
simply go to the keyboard configuration and search for the german layouts

**Expected behavior**
I tried all the present layouts but none worked .... if the position of Y and Z are ok there are instead the special german character that don't fit .... 

**Screenshots**
![image](https://user-images.githubusercontent.com/102513602/160360499-830feb36-186e-49b8-8466-1133ca64ae91.png)

**Desktop (please complete the following information):**
 - OS Nitrux 
 - Browser
 - Version 2.0.1
 - etc.

**Additional context**

**Comment by UriHerrera** [comment]
Typing 'german' in the search box of the Input Devices KCM>Keyboard dialog displays 41 layouts available in Plasma 5.24.4. If none of these results matches your physical keyboard, then it's a bug in Plasma.

We don't add (or remove) keyboard layouts.

![image_2022-03-31_22-49-03](https://user-images.githubusercontent.com/3053525/161196891-f2c4da37-40d1-4d4c-a67a-575e4ef8dbbd.png)
