### ISSUE TITLE
wrong faq url on nxos.org main website

### ISSUE THREAD

**Issue by totedati** [Nitrux/nitrux-bug-tracker#6]
Title is self explanatory ... almost. At [nxos.org](https://nxos.org/) main web page you click "Download Nitrux" button then go to "Download Nitrux" again, you click! then you get down to real download link. Here you are urged to read the faq before any real install, you find that faq so you click! "Read our Faq" button ... and you are going back to the same web page by some url indirections because "Read our Faq" url is not here. [Read our Faq](https://nxos.org/es/nxos/faq/) url is wrong, the working faq url is [Nitrux Faq](https://nxos.org/en/nitrux/faq/) and you find it using the good ol' google friend.

**Comment by UriHerrera** [comment]
fixed

**Comment by totedati** [comment]
Confirmed ...
