### ISSUE TITLE
Screen frozen after logging in 

### ISSUE THREAD

**Issue by thatcatdrout** [Nitrux/nitrux-bug-tracker#60]
**Describe the bug**
When i log into the live iso my screen gets frozen/stuck and nothing more happends. I have a Nvidia GTX 660 graphics card 

**To Reproduce**
1. Get a Nvidia GTX 660 GPU and install it
2. boot into the live ISO
3. Screen stuck

**Expected behavior**
It should boot normally into the Live enviroment and be able to install

**Desktop (please complete the following information):** (the os used to burn the image)
 - OS: Windows 10 21H2
 - Browser: Firefox
 - Version: latest
 - tool used to burn the iso to a usb drive: Rufus 

**Additional context**
Probably something to do with wayland not sure

**Comment by UriHerrera** [comment]
_Which screen_? The GRUB menu? Plymouth? SDDM? Plasma splash screen (Ksplash)?.

Please be more descriptive, add more information, and add screenshots or videos.

- What have you tried? i.e., Have you tested no nomodeset? Other GRUB parameters? Use a different TTY to start X11 and see what errors it shows? Etc.
- Does the Nouveau driver load? Does it load but X11 crashes?.

The latest Nvidia driver to support your GPU is 470.103.01; this driver is available to install.

**Comment by UriHerrera** [comment]
Please be more descriptive, add more information, and add screenshots or videos.

    What have you tried? i.e., Have you tested nomodeset? Other GRUB parameters? Use a different TTY to start X11 and see what errors it shows? Etc.
    Does the Nouveau driver load? Does it load but X11 crashes? Does Plasma crash?.

The latest Nvidia driver to support your GPU is 470.103.01; this driver is available to install.

We don't include any Wayland sessions anymore, so that's not the problem.

**Comment by thatcatdrout** [comment]
Tried also the minimal Nitrux ISO it does work but im unsure how to start the installer on that version

**Comment by UriHerrera** [comment]
> Tried nomodeset does not work After burning the ISO with Ventoy, Rufus and Etcher i now get this when trying to boot into the live enviroment [![IMG-20220413-110411.jpg](https://camo.githubusercontent.com/a84c4f3d3c4daced2c33f72a7504d94568e1a0489ef56a4f8cf26ebf5b16764a/68747470733a2f2f692e706f7374696d672e63632f6474705a575838512f494d472d32303232303431332d3131303431312e6a7067)](https://postimg.cc/hf8Gv2yN)

This error is from an incorrect flashing. As you can read from the error, there's a problem mounting the SquashFS file.

**Comment by thatcatdrout** [comment]
My issue has not been resolved but i already installed a distro meanwhile so i think i will close this
