### ISSUE TITLE
latte-dock not autostarting and command not found

### ISSUE THREAD

**Issue by Sarcasmo220** [Nitrux/nitrux-bug-tracker#63]
**Describe the bug**
Latte Dock does not load at startup, and cannot be manually started through terminal. Terminal states "command not found" and when running autostart-latte there is an error that says "command not found: latte-dock." It appears to be for 

**To Reproduce**
1. Log in to desktop session
2. latte-dock does not run

**Expected behavior**
Latte Dock will load at login with panel and/or launcher

**Desktop (please complete the following information):**
Operating System: Nitrux 2.1.0 build.310322
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.93.0
Qt Version: 5.15.3
Kernel Version: 5.15.32-051532-generic (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-7300HQ CPU @ 2.50GHz
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050/PCIe/SSE2
 - latte-dock version .10.801+nitrux+git

**Comment by UriHerrera** [comment]
Issue solved in https://github.com/Nitrux/latte-dock/commit/6ad2aaf5ecc44833da22d076058bd043ae11d09a
