### ISSUE TITLE
Help installing Nitrux

### ISSUE THREAD

**Issue by Leoarchie** [Nitrux/nitrux-bug-tracker#69]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS
Nitrux 2.1.1
 - Version
 - etc.

**Additional context**
When I start the setup to install nitrux is 2.1.1 I get to the partitions section and it doesn't display the remove button to delete my previous software and the button you click to start to install is greyed out and I don't know how to complete the partitions section, I just don't know how to proceed further I am new to Linux I've moved from Windows 10. Many thanks, Paul Giles

**Comment by UriHerrera** [comment]
We have an installation tutorial on our site https://nxos.org/tutorial/how-to-install-nitrux/.
