### ISSUE TITLE
Gunk at the top of the lock screen

### ISSUE THREAD

**Issue by HeyZoos** [Nitrux/nitrux-bug-tracker#7]
**Describe the bug**
Gunk at the top of the lock screen

**To Reproduce**
1. Fresh install of Nitrux 1.2.4 using a legacy installer
2. Lock the screen

**Expected behavior**
No gunk

**Screenshots**
![loginscreen](https://user-images.githubusercontent.com/9408481/72457322-55a84500-3794-11ea-854f-a0463afa26fe.png)

**Desktop (please complete the following information):**
```
NAME="Nitrux"
VERSION="1.2.4-Legacy"
ID=nxos
ID_LIKE=ubuntu
PRETTY_NAME="Nitrux 1.2.4-Legacy"
VERSION_ID="1.2.4-Legacy"
HOME_URL="https://nxos.org/"
SUPPORT_URL="https://nxos.org/"
BUG_REPORT_URL="https://github.com/Nitrux/nitrux-bug-tracker"
VERSION_CODENAME=nxos
UBUNTU_CODENAME=bionic
```

**Comment by UriHerrera** [comment]
What GPU do you have?. I have noticed this behavior on AMD hardware precisely at the lock screen. And sometimes, it also happens with Nvidia hardware after waking up from suspend.

To rule out that's our stuff, does this happen with other look and feel packages? If it does happen with a different look and feel package, then it's an issue with the driver and KWin. You may want to reload KWin to fix it.

If it doesn't happen with other look and feel packages, then it's a problem with ours.
