### ISSUE TITLE
There is no pro audio profile in audio settings

### ISSUE THREAD

**Issue by mn-xd** [Nitrux/nitrux-bug-tracker#75]
### Is your proposal related to a problem?

I need pro audio profile for my headphones to work properly, but it seems like there isn't anything like that.

I switched from gnome, where there was this profile. 

### Describe alternatives you've considered

I couldn't find anything other to work with my headphones

### Additional context

(Write your answer here.)

**Comment by UriHerrera** [comment]
Please add more information about this feature request. 

- Can you please point me to a distribution that includes this feature?
- I have searched for "Gnome Audio Profiles," and all I find is a link to this: https://help.gnome.org/users/gnome-audio-profiles/stable/gnome-audio-profiles-usage.html.en; however, the screenshots there are clearly from very old releases of Gnome.
- I'm running a Fedora VM; if I go to Configuration>Sound, I cannot find where to change the audio profile in the same way that Plasma lists these profiles. But I assume that it's this dropdown menu labeled _Configuration_.
![VirtualBox_Fedora_11_08_2022_17_19_53](https://user-images.githubusercontent.com/3053525/184252355-c1f4bc3e-c65a-4b3c-b9ab-2903d7dd72e7.png)
![Screenshot_20220811_172010](https://user-images.githubusercontent.com/3053525/184252375-5a011d21-58cb-4889-af5d-123c3d8d3593.png)
    - If Gnome listed the profile in this dropdown, then it's likely that I don't see it listed because this is a VM.
- From this post: https://unix.stackexchange.com/questions/675239/the-pro-audio-profile-in-pipewire-for-audio-devices-sound-cards, it __sounds__ to me (pun intended) that whatever Gnome distribution you were using was using PipeWire. By default, we don't use PipeWire; we use PulseAudio; however, you can switch to PipeWire following this tutorial: https://nxos.org/tutorial/how-to-use-wayland-and-pipewire-in-nitrux/. This post in the Manjaro forums also points to that: https://forum.manjaro.org/t/what-is-pro-audio/56606.
