### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by UnseenVoid** [Nitrux/nitrux-bug-tracker#77]
During Installation it's show Error:
>Link Creation Failed Timezone Error (Asia/ Kolkata)

Unable to install Nitrux because of this error. I can't find any solution for this.

**Comment by UriHerrera** [comment]
Please run `sudo -E calamares -d` and paste the output (also, please format it.)

**Comment by UnseenVoid** [comment]
> Please run `sudo -E calamares -d` and paste the output (also, please format it.)

Thanks brother
Issue Solved!!💓💓

I really love using Nitrux OS
Looking forward to contribute to Nitrux OS
