### ISSUE TITLE
Bootloader Installation Error

### ISSUE THREAD

**Issue by Nsafhi** [Nitrux/nitrux-bug-tracker#83]
![photo_٢٠٢٢-١١-١٥_٠١-٥٦-٥٧](https://user-images.githubusercontent.com/118226675/201787556-f59c09d3-8a78-4a59-98c7-5803be4347f5.jpg)

**Describe the bug**
Nitrux failed to make a portion after that I turn off the computer without fully installing the OS 
Then the live option disappeared.

**Comment by Nsafhi** [comment]
there is already someone with the same issue sorry.

**Comment by UriHerrera** [comment]
> Nitrux failed to make a portion after that I turn off the computer without fully installing the OS
Then the live option disappeared.

I'm sorry @Nsafhi I do not understand what you're saying.

**Comment by Nsafhi** [comment]
I did not do a manually partitioning.

**Comment by Nsafhi** [comment]
I reinstalled the system via usb it works now sorry for the trouble.

**Comment by Nsafhi** [comment]
![photo_2022-11-15_11-24-39](https://user-images.githubusercontent.com/118226675/201867790-837d0d81-08aa-4ab9-91bc-dcb7f75595ac.jpg)

**Comment by Nsafhi** [comment]
@UriHerrera sir, can you help me with the bootloader error?

**Comment by Nsafhi** [comment]
OS: 2.5.0

**Comment by UriHerrera** [comment]
@Nsafhi Please do not add multiple single-line comments. Edit your original comment and add the relevant information.
