### ISSUE TITLE
nvidia-settings has a lot missing settings

### ISSUE THREAD

**Issue by AmerXz** [Nitrux/nitrux-bug-tracker#87]
**Description**
I don't know how can I use this distro with my old nvidia optimus GPU because  nvidia-settings doesn't show the options I needed. 

**To Reproduce**
1. Having Kepler optimus GPU (mine is 765m)
2. running nvidia-settings
3. Seeing the missing options
4. Try to install older version of nvidia drivers ( I do that on most other distros)
5. Realized that there was no package manager and I didn't know how can I fix that

**Expected behavior**
Being Able to get my nvidia GPU to work on this distro.

**Not Very Important**
Other than that thank you for the great distro with it's very unique philosophy.

**Comment by UriHerrera** [comment]
Unfortunately, we do not develop the Nvidia proprietary driver. Please ask Nvidia to fix this issue. 

https://nvidia.custhelp.com/app/answers/detail/a_id/4512/~/i-found-a-bug%2C-where-do-i-go-to-report-it%3F

**Comment by AmerXz** [comment]
I think my question was not clear I wanted to find a way to install other nvidia versions such as 470xx 390xx etc

**Comment by UriHerrera** [comment]
@AmerXz You can't, and we can't include multiple versions of this driver. We can only include one version, which will be the latest available. 

It's also impossible to install [multiple versions of the Nvidia proprietary driver](https://forums.developer.nvidia.com/t/multiple-nvidia-drivers/34946), so using the "runfile" is not an option.

**Comment by AmerXz** [comment]
Thanks For Reply
