### ISSUE TITLE
Nitrux 2.6.0 no sound on my 2020 Dell 9710 

### ISSUE THREAD

**Issue by BoardWatcher** [Nitrux/nitrux-bug-tracker#88]
I tried out 2.6.0 on my 2020 Dell 9710 laptop And found that the distro does not offer any Intel sound sinks. Other Ubuntu Linux distros on the same laptop install the TigerLake drivers which provide sound support. Please provide a way to install hardware drivers to your distro.

**Comment by UriHerrera** [comment]
According to [this question in Ask Ubuntu](https://askubuntu.com/questions/1384538/no-sound-dell-xps-17-9700-ubuntu-21-10), you can try adding `options snd-hda-intel model=headset-multi` to `/etc/modprobe.d/alsa-base.conf` and see if that changes something for you.

Although we're using ALSA, we use PipeWire. We also don't use the Ubuntu kernel (or any Ubuntu sources or build Nitrux from an Ubuntu rootfs), so if audio works for you in Ubuntu-based distributions, that could be a reason.

You can also try changing the audio profile in System Settings>Sound. As drivers are concerned, we include firmware for Intel SOF audio; perhaps your hardware isn't supported by the included firmware files; if that's the case, please wait for a new release with updated content.

**Comment by UriHerrera** [comment]
According to [this question in Ask Ubuntu](https://askubuntu.com/questions/1384538/no-sound-dell-xps-17-9700-ubuntu-21-10), you can try adding `options snd-hda-intel model=headset-multi` to `/etc/modprobe.d/alsa-base.conf` and see if that changes something for you.

Although we're not using ALSA, we use PipeWire. We also don't use the Ubuntu kernel (or any Ubuntu sources or build Nitrux from an Ubuntu rootfs), so if audio works for you in Ubuntu-based distributions, that could be a reason.

You can also try changing the audio profile in System Settings>Sound. As drivers are concerned, we include firmware for Intel SOF audio; perhaps your hardware isn't supported by the included firmware files; if that's the case, please wait for a new release with updated content.
