### ISSUE TITLE
Nitrux 2.7.0 - NX Software Center Doesn't Open

### ISSUE THREAD

**Issue by eliasibero** [Nitrux/nitrux-bug-tracker#89]
I have installed Nitrux 2.7.0 on My Dell Precision Tower 5820 with no problem.
When I try to open NX Software Center from the Desktop or from the KDELink it won't open. No error is reported.

**Comment by UriHerrera** [comment]
A new ISO was uploaded, `nitrux-nx-desktop-plasma-bd04e074-amd64.iso`, to fix this problem.

As we indicated in our [PSA](https://nxos.org/psa/psa-nitrux-2-7-0/), you've already installed the distribution do the following:

```
sudo ln -sv /usr/lib/x86_64-linux-gnu/libappimage.so.1.0.3.abi1 /usr/lib/x86_64-linux-gnu/libappimage.so.1.0
```

Please see [Working with overlayroot in Nitrux](https://nxos.org/notes/notes-nitrux-2-7-0/#working-with-overlayroot-in-nitrux) to know how to make this change permanent.

**Comment by eliasibero** [comment]
Thank you for your quick response. I will give a try.Thank you again! 


Sent from AT&T Yahoo Mail for iPhone


On Tuesday, March 7, 2023, 8:45 AM, Uri Herrera ***@***.***> wrote:




A new ISO was uploaded, nitrux-nx-desktop-plasma-bd04e074-amd64.iso, to fix this problem.

As we indicated in our PSA, you've already installed the distribution do the following:
sudo ln -sv /usr/lib/x86_64-linux-gnu/libappimage.so.1.0.3.abi1 /usr/lib/x86_64-linux-gnu/libappimage.so.1.0

Please see Working with overlayroot in Nitrux to know how to make this change permanent.
