### ISSUE TITLE
Automatic login doesnt work with plasma wayland session

### ISSUE THREAD

**Issue by sprc9034** [Nitrux/nitrux-bug-tracker#91]
The automatic login works for plasma(X11), but when you go to system settings->startup and shutdown->behaviour->automatic login-> plasma(wayland). The system reboots fine but doesnt save the setting and boots back into plasma(X11) session.
Expected behavior: reboot and automatic login into plasma (wayland)

**Comment by UriHerrera** [comment]
We do not develop SDDM, Plasma Wayland, or KWin Wayland. Please file bugs for KDE software at the [KDE Bugtracking System](https://bugs.kde.org/).

**Comment by sprc9034** [comment]
Thanks for the prompt reply, I didn't go through the notes for the last release as I had a screen tearing issue and hence uninstalled the distro. BTW the 2.7.0 release is great keep up the good work.
