### ISSUE TITLE
Maui Shell crashes in Nitrux 2.7.0 (Maui Shell ISO)

### ISSUE THREAD

**Issue by mcder3** [Nitrux/nitrux-bug-tracker#92]
**Describe the bug**
Maui Shell crashes randomly while I'm using the distribution, and apps like Station go black without showing me the terminal.

After getting a black screen, it is impossible to change to a TTY, and the only way to recover the PC is to restart it with <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>SUPR</kbd>

**To Reproduce**
1. This problem occurs randomly

**Expected behavior**
No crashes.

**Desktop (please complete the following information):**
 - OS: Nitrux ISO with Maui Shell f5f3e48f
 - Version:  2.7.0

**Comment by UriHerrera** [comment]
La voy a cerrar por el moment ya que el ISO no esta disponible.
