### ISSUE TITLE
Installation failed - SSL error

### ISSUE THREAD

**Issue by BalaDhinesh** [Nitrux/nitrux-bug-tracker#93]
I tried installing Nitrux latest OS version 2.7.0 from USB live stick using manual partitioning and I got the following installation error:

```
Installation failed:
External command finished with errors
Details:
Command <i>axel -a -o //bin -n 10 https://raw.githubusercontent.com/Nitrux/iso-tool/legacy/configs/scripts/linker</i> finished with exit code 1.
Output:
SSL error:(null)
Initializing download: https://raw.githubusercontent.com/Nitrux/iso-tool/legacy/configs/scripts/linker
(null)
```

Please help in this regard. Thanks!

**Comment by UriHerrera** [comment]
That indicates a problem with your connection to GitHub. The command works, and the file exists in the URL.

![image](https://user-images.githubusercontent.com/3053525/224247032-3d4b87ee-8ddf-4592-bc0a-adc9aa08f336.png)
