### ISSUE TITLE
installer fails: rsync failed with error code 11 (disk full)

### ISSUE THREAD

**Issue by ernest-bruce** [Nitrux/nitrux-bug-tracker#98]
when i try to install Nitux 2.7.0 on VirtualBox 7.0.6 on macOS 12.6.3 using nitrux-nx-desktop-plasma-bd04e074-amd64.iso, i get:
<img width="1117" alt="install_fails" src="https://user-images.githubusercontent.com/6908514/227769496-950347b7-a8ef-4091-99e6-93787979dbe7.png">

1. create vm in VirtualBox:
- name: nitrux270
- type: Linux
- version: Debian 10 Buster (64-bit)
- memory: 4096MB
- processors: 2
- √ enable EFI (special OSes only)
- √ create Virtual Hard Disk Now: 30.55 GB, √ pre-allocate full size

vm summary:
<img width="1167" alt="vm_creation_summary" src="https://user-images.githubusercontent.com/6908514/227770017-ec8c7243-6e1e-4168-b659-afabcf78b5e6.png">

3. power on nitrux270 vm
4. select Boot Nitrux (Live); press Enter
5. click Install Nitrux
<img width="1136" alt="welcome_to_nitrux" src="https://user-images.githubusercontent.com/6908514/227770327-0fbe1131-ba5c-49ce-9bc8-8758ca4fbc5a.png">

6. click Next
7. click America, select Los Angeles (this part is awkward, i get New York timezone), click Next
8. click Next
9. enter user and log·in info, click Next
10. select “Erase disk”:
<img width="1136" alt="erase_disk" src="https://user-images.githubusercontent.com/6908514/227770690-d47aa1cb-1497-433e-b2d6-f7d71e505cf4.png">

12. click Next, installation summary appears:
<img width="1092" alt="installation_summary" src="https://user-images.githubusercontent.com/6908514/227770832-49c95279-de9b-45c3-8cdb-b2e992e15615.png">

14. click Install
15. click Install Now

at about 13%, error message appears

**Expected behavior**
successful installation

**Comment by UriHerrera** [comment]
If you check your fourth image, where the partitions are laid out, you can see that the root partition (NX_ROOTD) is only 5.45 GiB or ~5.85 GB, meaning there's insufficient space for Calamares to decompress the SquashFS to the root partition.

The partition layout assumes that a 32 GB device will be used, as the configuration for the partitions module sets the size in percentages, as explained in the changelog for [Nitrux 2.6.0](https://nxos.org/changelog/release-announcement-nitrux-2-6-0/).

Use a larger virtual device.
